{
 "title": "Cassandra Dashboard (corrected by th2 team)",
 "tags": [
  "cassandra",
  "salt",
  "java",
  "cortex"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "keyspace",
    "query": {
     "query": "label_values(cassandra_table_totaldiskspaceused_count, keyspace)"
    }
   },
   {
    "name": "table",
    "query": {
     "query": "label_values(cassandra_table_totaldiskspaceused_count{keyspace=\"$keyspace\"}, table)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(cassandra_table_totaldiskspaceused_count, instance)"
    }
   },
   { "name": "interval", "query": "1m" }
  ]
 },
 "panels": [
  {
   "title": "Node Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "cassandra_storage_load_count", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "STATUS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"cassandra\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cassandra_client_connectednativeclients{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Availabilty",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (sum by (instance) (irate(jvm_gc_collection_seconds_sum{ instance=~\"$instance\",}[3m])))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "GC Count / s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_collection_seconds_count{instance=~\"$instance\"}[3m])",
     "legendFormat": "{{ instance }} - {{ gc }}"
    }
   ]
  },
  {
   "title": "Avg GC Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_collection_seconds_sum{instance=~\"$instance\"}[3m]) / irate(jvm_gc_collection_seconds_count{instance=~\"$instance\"}[3m])",
     "legendFormat": "{{ instance }} - {{ gc }}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - max"
    },
    {
     "expr": "jvm_memory_bytes_committed{area=\"heap\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - committed"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - used"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{area=\"nonheap\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - max"
    },
    {
     "expr": "jvm_memory_bytes_committed{area=\"nonheap\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - committed"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - used"
    }
   ]
  },
  {
   "title": "Heap Used (Old Gen)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=~\".*[Oo]ld.*\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - max {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=~\".*[Oo]ld.*\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - committed {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=~\".*[Oo]ld.*\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - used - {{ pool }}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_peak{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - peak"
    },
    {
     "expr": "jvm_threads_daemon{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - daemon"
    },
    {
     "expr": "jvm_threads_current{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - current"
    },
    {
     "expr": "jvm_threads_deadlocked{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - deadlocked"
    }
   ]
  },
  {
   "title": "Direct Buffer Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_pool_capacity_bytes{pool=\"direct\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - capacity"
    },
    {
     "expr": "jvm_buffer_pool_used_bytes{pool=\"direct\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - used"
    }
   ]
  },
  {
   "title": "Mapped Buffer Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_pool_capacity_bytes{pool=\"mapped\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - capacity"
    },
    {
     "expr": "jvm_buffer_pool_used_bytes{pool=\"mapped\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - used"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{job=\"cassandra\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - max"
    },
    {
     "expr": "process_open_fds{job=\"cassandra\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - open"
    }
   ]
  },
  {
   "title": "JVM MEMORY DETAIL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Heap - Eden",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{instance=~\"$instance\", pool=~\".*[eE]den.*\"}",
     "legendFormat": "{{ instance }} - max {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{instance=~\"$instance\", pool=~\".*[eE]den.*\"}",
     "legendFormat": "{{ instance }} - committed {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$instance\", pool=~\".*[eE]den.*\"}",
     "legendFormat": "{{ instance }} - used {{ pool }}"
    }
   ]
  },
  {
   "title": "NonHeap - Metaspace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{instance=~\"$instance\", pool=~\".*[mM]eta.*\"}",
     "legendFormat": "{{ instance }} - max {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{instance=~\"$instance\", pool=~\".*[mM]eta.*\"}",
     "legendFormat": "{{ instance }} - committed {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$instance\", pool=~\".*[mM]eta.*\"}",
     "legendFormat": "{{ instance }} - used {{ pool }}"
    }
   ]
  },
  {
   "title": "Heap - Survivor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{instance=~\"$instance\", pool=~\".*[sS]urvivor.*\"}",
     "legendFormat": "{{ instance }} - max {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{instance=~\"$instance\", pool=~\".*[sS]urvivor.*\"}",
     "legendFormat": "{{ instance }} - committed {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$instance\", pool=~\".*[sS]urvivor.*\"}",
     "legendFormat": "{{ instance }} - used {{ pool }}"
    }
   ]
  },
  {
   "title": "NonHeap - Code Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{instance=~\"$instance\", pool=~\".*[cC]ode.*\"}",
     "legendFormat": "{{ instance }} - max {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{instance=~\"$instance\", pool=~\".*[cC]ode.*\"}",
     "legendFormat": "{{ instance }} - committed {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$instance\", pool=~\".*[cC]ode.*\"}",
     "legendFormat": "{{ instance }} - used {{ pool }}"
    }
   ]
  },
  {
   "title": "Heap - Old",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{instance=~\"$instance\", pool=~\".*[oO]ld.*\"}",
     "legendFormat": "{{ instance }} - max {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{instance=~\"$instance\", pool=~\".*[oO]ld.*\"}",
     "legendFormat": "{{ instance }} - committed {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$instance\", pool=~\".*[oO]ld.*\"}",
     "legendFormat": "{{ instance }} - used {{ pool }}"
    }
   ]
  },
  {
   "title": "NonHeap - Compressed Class Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{instance=~\"$instance\", pool=~\".*[cC]lass.*\"}",
     "legendFormat": "{{ instance }} - max {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{instance=~\"$instance\", pool=~\".*[cC]lass.*\"}",
     "legendFormat": "{{ instance }} - committed {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$instance\", pool=~\".*[cC]lass.*\"}",
     "legendFormat": "{{ instance }} - used {{ pool }}"
    }
   ]
  },
  {
   "title": "CLUSTER - $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Reads / s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cassandra_keyspace_readlatency_seconds_count{keyspace=\"$keyspace\", instance=~\"$instance\"}[3m])) > 0",
     "legendFormat": "reads"
    }
   ]
  },
  {
   "title": "Writes / s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cassandra_keyspace_writelatency_seconds_count{keyspace=\"$keyspace\", instance=~\"$instance\"}[3m]))",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "Connection Timeouts / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (connection) (irate(cassandra_connection_timeouts_count{instance=~\"$instance\"}[3m]))",
     "legendFormat": "dst {{ connection }}"
    }
   ]
  },
  {
   "title": "Client Timeouts And Failures / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cassandra_clientrequest_timeouts_count{instance=~\"$instance\"}[3m]))",
     "legendFormat": "timeout"
    },
    {
     "expr": "sum(irate(cassandra_clientrequest_failures_count{instance=~\"$instance\"}[3m]))",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_totaldiskspaceused{instance=~\"$instance\"})",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Disk Used by instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 110 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (cassandra_keyspace_totaldiskspaceused{instance=~\"$instance\"})",
     "legendFormat": "{{ instance }} - used"
    }
   ]
  },
  {
   "title": "Compaction / 2m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cassandra_compaction_bytescompacted_count{instance=~\"$instance\"}[2m]))"
    }
   ]
  },
  {
   "title": "Hints Service  / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cassandra_hintsservice_hintsfailed_count{instance=~\"$instance\"}[3m]))",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(irate(cassandra_hintsservice_hintstimedout_count{instance=~\"$instance\"}[3m]))",
     "legendFormat": "timeout"
    },
    {
     "expr": "sum(irate(cassandra_hintsservice_hintssucceeded_count{instance=~\"$instance\"}[3m]))",
     "legendFormat": "succeeded"
    }
   ]
  },
  {
   "title": "Dropped Messages / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (droppedmessage) (irate(cassandra_droppedmessage_dropped_count{instance=~\"$instance\"}[3m]))",
     "legendFormat": "{{ droppedmessage }}"
    }
   ]
  },
  {
   "title": "Compaction Tasks / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cassandra_compaction_completedtasks{instance=~\"$instance\"}[3m]))",
     "legendFormat": "completed"
    },
    {
     "expr": "sum(irate(cassandra_compaction_pendingtasks{instance=~\"$instance\"}[3m]))",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "Prepared Statements Ratio",
   "type": "graph",
   "description": "Percentage of statements that are prepared vs unprepared.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(cassandra_cql_preparedstatementsratio{instance=~\"$instance\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "CAS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cassandra_keyspace_cascommitlatency_seconds_count{ keyspace=\"$keyspace\"}[3m]))",
     "legendFormat": "CAS commit"
    },
    {
     "expr": "sum(irate(cassandra_keyspace_caspreparelatency_seconds_count{ keyspace=\"$keyspace\"}[3m]))",
     "legendFormat": "CAS prepare"
    },
    {
     "expr": "sum(irate(cassandra_keyspace_casproposelatency_seconds_count{ keyspace=\"$keyspace\"}[3m]))",
     "legendFormat": "CAS propose"
    }
   ]
  },
  {
   "title": "Thread Pools Active Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 143 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster, path, threadpools) (cassandra_threadpools_activetasks{instance=~\"$instance\"})",
     "legendFormat": "{{ path }}: {{ threadpools }}"
    }
   ]
  },
  {
   "title": "Thread Pools Completed Tasks / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 151 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster, path, threadpools) (irate(cassandra_threadpools_completedtasks{instance=~\"$instance\"}[3m]))",
     "legendFormat": "{{ path }}: {{ threadpools }}"
    }
   ]
  },
  {
   "title": "Thread Pools Pending Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 159 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster, path, threadpools) (cassandra_threadpools_pendingtasks{instance=~\"$instance\"})",
     "legendFormat": "{{ path }}: {{ threadpools }}"
    }
   ]
  },
  {
   "title": "Threadpools Max Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 167 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_threadpools_maxpoolsize{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - {{ path }} {{ threadpools }}"
    }
   ]
  },
  {
   "title": "Threadpools Total Blocked Tasks / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 175 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster, path, threadpools) (irate(cassandra_threadpools_totalblockedtasks_count{instance=~\"$instance\"}[3m]))",
     "legendFormat": "{{ path }} {{ threadpools }}"
    }
   ]
  },
  {
   "title": "Cache Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 183 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (cache) (cassandra_cache_capacity{ instance=~\"$instance\"})",
     "legendFormat": "{{ cache }}"
    }
   ]
  },
  {
   "title": "Col Update Time Delta",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 183 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(cassandra_keyspace_colupdatetimedeltahistogram{ keyspace=\"$keyspace\", quantile=\"0.50\", instance=~\"$instance\"})",
     "legendFormat": "50 percentile"
    },
    {
     "expr": "avg(cassandra_keyspace_colupdatetimedeltahistogram{ keyspace=\"$keyspace\", quantile=\"0.99\", instance=~\"$instance\"})",
     "legendFormat": "99 percentile"
    }
   ]
  },
  {
   "title": "The number of SSTables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 191 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_table_livesstablecount{ keyspace=\"$keyspace\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CLIENT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 199 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Reads / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 200 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster, clientrequest) (irate(cassandra_clientrequest_latency_seconds_count{clientrequest!~\"Read|.*Write.*\", instance=~\"$instance\"}[3m]))",
     "legendFormat": "{{ clientrequest }} "
    }
   ]
  },
  {
   "title": "Writes / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 200 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster, clientrequest) (irate(cassandra_clientrequest_latency_seconds_count{clientrequest!~\"Write|.*Read.*|RangeSlice\", instance=~\"$instance\"}[3m]))",
     "legendFormat": "{{ clientrequest }}"
    }
   ]
  },
  {
   "title": "Client Read Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 207 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (cluster) (cassandra_clientrequest_latency_seconds{quantile=\"0.99\", clientrequest=~\".*Read.*\", instance=~\"$instance\"})",
     "legendFormat": "99p"
    },
    {
     "expr": "max by (cluster) (cassandra_clientrequest_latency_seconds{quantile=\"0.95\", clientrequest=~\".*Read.*\", instance=~\"$instance\"})",
     "legendFormat": "95p"
    },
    {
     "expr": "max by (cluster) (cassandra_clientrequest_latency_seconds{quantile=\"0.75\", clientrequest=~\".*Read.*\", instance=~\"$instance\"})",
     "legendFormat": "75p"
    }
   ]
  },
  {
   "title": "Client Write Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 207 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (cluster) (cassandra_clientrequest_latency_seconds{instance=~\"$instance\", quantile=\"0.99\", clientrequest=~\".*Write.*\"})",
     "legendFormat": "99p"
    },
    {
     "expr": "max by (cluster) (cassandra_clientrequest_latency_seconds{instance=~\"$instance\", quantile=\"0.95\", clientrequest=~\".*Write.*\"})",
     "legendFormat": "95p"
    },
    {
     "expr": "max by (cluster) (cassandra_clientrequest_latency_seconds{instance=~\"$instance\", quantile=\"0.75\", clientrequest=~\".*Write.*\"})",
     "legendFormat": "75p"
    }
   ]
  },
  {
   "title": "Client Timeouts and Failures / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 214 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster) (irate(cassandra_clientrequest_timeouts_count{instance=~\"$instance\"}[3m]))",
     "legendFormat": "timeout"
    },
    {
     "expr": "sum by (cluster) (irate(cassandra_clientrequest_failures_count{instance=~\"$instance\"}[3m]))",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Client Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 221 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_client_connectednativeclients{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - native"
    },
    {
     "expr": "cassandra_client_connectedthriftclients{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - thrift"
    }
   ]
  },
  {
   "title": "Client Authorizations / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 229 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster) (irate(cassandra_client_authsuccess_count{instance=~\"$instance\"}[3m]))",
     "legendFormat": "success"
    },
    {
     "expr": "sum by (cluster) (irate(cassandra_client_authfailure_count{instance=~\"$instance\"}[3m]))",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "MEMTABLE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 237 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memtable Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 238 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (cassandra_table_allmemtablesheapsize{ keyspace=\"$keyspace\", instance=~\"$instance\"})",
     "legendFormat": "{{ instance }} - heap"
    },
    {
     "expr": "sum by (instance) (cassandra_table_allmemtablesoffheapsize{ keyspace=\"$keyspace\", instance=~\"$instance\"})",
     "legendFormat": "{{ instance }} - off_heap"
    }
   ]
  },
  {
   "title": "Memtable Switch Count / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 238 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(cassandra_table_memtableswitchcount{ instance=~\"$instance\"}[3m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Waiting on free memtable space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 246 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (cassandra_table_waitingonfreememtablespace{ quantile=\"0.50\", instance=~\"$instance\"})",
     "legendFormat": "{{ instance }} - 50 percentile"
    },
    {
     "expr": "sum by (instance) (cassandra_table_waitingonfreememtablespace{ quantile=\"0.99\", instance=~\"$instance\"})",
     "legendFormat": "{{ instance }} - 99 percentile"
    }
   ]
  },
  {
   "title": "Bloomfilter disk space used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 246 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_keyspace_bloomfilterdiskspaceused{ keyspace=\"$keyspace\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - used"
    }
   ]
  },
  {
   "title": "Flushed / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 254 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(cassandra_table_bytesflushed{ instance=~\"$instance\"}[3m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "TABLE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 262 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Reads / s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 263 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by (table) (irate(cassandra_table_readlatency_seconds_count{ keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"}[3m])))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Writes / s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 263 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by (table) (irate(cassandra_table_writelatency_seconds_count{keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"}[3m])))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Read Latency (95%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 272 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, max by (table) (cassandra_table_readlatency_seconds{keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\", quantile=\"0.95\"}))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Write Latency (95%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 272 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, max by (table) (cassandra_table_writelatency_seconds{keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.95\"}))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Read Latency (99%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 278 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, max by (table) (cassandra_table_readlatency_seconds{keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\", quantile=\"0.99\"}))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Write Latency (99%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 278 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, max by (table) (cassandra_table_writelatency_seconds{keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\", quantile=\"0.99\"}))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Coordinator Read Latency (99%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 286 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, max by (table) (cassandra_table_coordinatorreadlatency_seconds{keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.99\"}))",
     "legendFormat": "{{ instance }} - {{ table }}"
    }
   ]
  },
  {
   "title": "Coordinator Scan Latency (99%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 286 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, max by (table) (cassandra_table_coordinatorscanlatency_seconds{keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.99\"}))",
     "legendFormat": "{{ instance }} - {{ table }}"
    }
   ]
  },
  {
   "title": "Dropped Mutations / s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 286 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by (cluster, table) (irate(cassandra_table_droppedmutations_count{keyspace=\"$keyspace\", table=~\"$table\"}[3m])))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Compaction Bytes Written / s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 292 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by (table) (irate(cassandra_table_compactionbyteswritten_count{keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"}[3m])))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Tombstones Scanned In Queries (99%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 292 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by (table) (cassandra_table_tombstonescannedhistogram{keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.99\"}))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Disk Used Top 10",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 298 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (table) (cassandra_table_totaldiskspaceused_count{keyspace=\"$keyspace\", table=~\"$table\"}))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "[DPRECATED] TABLE TOP 10 by instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 314 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 315 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "topk(10, irate(cassandra_table_readlatency_seconds_count{keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"}[3m]) * 60)",
     "legendFormat": "{{ instance }} - {{ table }}"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 315 },
   "yaxes": [
    { "format": "wpm" }
   ],
   "targets": [
    {
     "expr": "topk(10, irate(cassandra_table_writelatency_seconds_count{keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"}[3m]) * 60)",
     "legendFormat": "{{ instance }} - {{ table }}"
    }
   ]
  },
  {
   "title": "Read Latency (95%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 321 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, cassandra_table_readlatency_seconds{keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\", quantile=\"0.95\"})",
     "legendFormat": "{{ instance }} - {{ table }}"
    }
   ]
  },
  {
   "title": "Write Latency (95%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 321 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, cassandra_table_writelatency_seconds{keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\", quantile=\"0.95\"})",
     "legendFormat": "{{ instance }} - {{ table }}"
    }
   ]
  },
  {
   "title": "Read Latency (99.9%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 327 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, cassandra_table_readlatency_seconds{keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.999\", instance=~\"$instance\"})",
     "legendFormat": "{{ instance }} - {{ table }}"
    }
   ]
  },
  {
   "title": "Write Latency (99.9%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 327 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, cassandra_table_writelatency_seconds{keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.999\", instance=~\"$instance\"})",
     "legendFormat": "{{ instance }} - {{ table }}"
    }
   ]
  },
  {
   "title": "Coordinator Read Latency (99.9%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 335 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, cassandra_table_coordinatorreadlatency_seconds{keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.999\", instance=~\"$instance\"})",
     "legendFormat": "{{ instance }} - {{ table }}"
    }
   ]
  },
  {
   "title": "Coordinator Write Latency (99.9%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 335 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, cassandra_table_coordinatorwritelatency_seconds{keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.999\", instance=~\"$instance\"})",
     "legendFormat": "{{ instance }} - {{ table }}"
    }
   ]
  },
  {
   "title": "Coordinator Scan Latency (99.9%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 335 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, cassandra_table_coordinatorscanlatency_seconds{keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.999\", instance=~\"$instance\"})",
     "legendFormat": "{{ instance }} - {{ table }}"
    }
   ]
  },
  {
   "title": "Compaction Bytes Written",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 341 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, cassandra_table_compactionbyteswritten_count{keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"} - cassandra_table_compactionbyteswritten_count{keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"} offset 1m)",
     "legendFormat": "{{ instance }} - {{ table }}"
    }
   ]
  },
  {
   "title": "Tombstones Scanned In Queries (99.9%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 341 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, cassandra_table_tombstonescannedhistogram{keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\", quantile=\"0.999\"})",
     "legendFormat": "{{ instance }} - {{ table }}"
    }
   ]
  },
  {
   "title": "Dropped Mutations For 1 Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 341 },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "expr": "topk(10, (cassandra_table_droppedmutations_count{keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"} - cassandra_table_droppedmutations_count{keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"} offset 1m))",
     "legendFormat": "{{ instance }} - {{ table }}"
    }
   ]
  },
  {
   "title": "Total Disk Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 347 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (instance) (cassandra_table_totaldiskspaceused_count{keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"}))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disk Used Per Table",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 347 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, cassandra_table_totaldiskspaceused_count{keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"})",
     "legendFormat": "{{ instance }} - {{ table }}"
    }
   ]
  }
 ]
}