{
 "title": "diagnostic dashboard v1.0.2",
 "tags": [ "namespace_health" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{namespace !~ \"kube-.*\"}, namespace)"
    }
   },
   {
    "name": "component",
    "label": "Log selector",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"$namespace\"},label_app)"
    }
   },
   { "name": "level", "label": "Log level", "query": "label_values({}, level)" },
   { "name": "servicens", "query": "${VAR_SERVICENS}" },
   { "name": "interval", "label": "Log interval", "query": "1m,10m,30m,1h,1d" }
  ]
 },
 "panels": [
  { "title": "General info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Th2-infra version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_labels{deployment=\"infra-editor\"}) by (label_helm_sh_chart)"
    }
   ]
  },
  {
   "title": "Total k8s Not Ready pods",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"$namespace\"} == 0)"
    }
   ]
  },
  {
   "title": "Total allocatable memory",
   "type": "stat",
   "description": "thresholds: \n&#x1F7E1; 4Gi\n&#x1F534; 2Gi",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n    (\n        kube_node_status_allocatable{resource=\"memory\"} \n    )\n    unless on (node)\n    kube_node_spec_taint{key!~\"node.kubernetes.io/.*\", effect=\"NoSchedule\"}    \n)"
    }
   ]
  },
  {
   "title": "Total allocatable CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n    (\n        kube_node_status_allocatable{resource=\"cpu\"} \n    )\n    unless on (node)\n    kube_node_spec_taint{key!~\"node.kubernetes.io/.*\", effect=\"NoSchedule\"}    \n)"
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "stat",
   "description": "thresholds: \n&#x1F7E1; 4Gi\n&#x1F534; 2Gi",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n    (\n        kube_node_status_allocatable{resource=\"memory\"} \n        - on (node)\n        sum by (node) (\n            container_memory_working_set_bytes{container!~\"|POD\", image!=\"\"}\n        )\n    )\n    unless on (node)\n    kube_node_spec_taint{key!~\"node.kubernetes.io/.*\", effect=\"NoSchedule\"}    \n)"
    }
   ]
  },
  {
   "title": "Available CPU",
   "type": "stat",
   "description": "thresholds: \n&#x1F7E1; 4 cores\n&#x1F534; 2 cores",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum((label_replace(sum by (instance) (rate(node_cpu_seconds_total{mode=~\"idle|iowait\"}[1m])), \"instance\", \"$1\", \"instance\", \"(.*):\\\\d+\") * on (instance) group_left(node) label_replace(kubelet_node_name, \"instance\", \"$1\", \"instance\", \"(.*):\\\\d+\")) unless on (node) kube_node_spec_taint)"
    }
   ]
  },
  { "title": "Components status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Core components readiness",
   "type": "stat",
   "gridPos": { "h": 3, "w": 20, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "kube_pod_container_status_ready{namespace=\"$namespace\", pod=~\"([em]store|rpt-data-[pv]).*\"}",
     "legendFormat": "{{pod}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "k8s readiness",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "kube_pod_container_status_ready{namespace=\"$namespace\", pod!~\"([em]store|rpt-data-[pv]).*\"}",
     "legendFormat": "{{pod}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  { "title": "Resourses usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "namespace health",
   "type": "table",
   "description": "thresholds: \n&#x1F7E1; 75%\n&#x1F534; 90%",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "k8s readiness"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\"}*1000) by (pod)",
     "legendFormat": "cpu_limit"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\"}/(1024*1024)) by (pod)",
     "legendFormat": "memory_limit"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\"} == 1) by (pod, phase)",
     "legendFormat": "phase"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting_reason{namespace=\"$namespace\"} == 1) by (pod, reason)",
     "legendFormat": "reasons"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=\"$namespace\"}) by (pod, image)",
     "legendFormat": "image"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "cpu_usage"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"\", image!=\"\"}) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "memory usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\"}*1000) by (pod)",
     "legendFormat": "cpu_request"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\"}) by (pod)",
     "legendFormat": "memory_request"
    },
    {
     "expr": "sum by(pod) (count_over_time({namespace=\"$namespace\", level=\"ERROR\"}[$interval]))",
     "legendFormat": "log_err"
    },
    {
     "expr": "sum by(pod) (round(increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[10m])))",
     "legendFormat": "restarts[10m]"
    },
    {
     "expr": "sum by(pod) (round(increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[1d])))"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Log message rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=\"$namespace\", app=~\"$component\", level=~\"$level\"}[1m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "$component logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "﻿{namespace=\"$namespace\", app=~\"$component\", level=~\"$level\"}"
    }
   ]
  }
 ]
}