{
 "title": "Infra dashboard",
 "time": { "from": "now-3d", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "label_values(namespace)" },
   {
    "name": "component",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"$namespace\"},label_app)"
    }
   },
   { "name": "commit", "label": "commit to search", "query": "96ba2ee8" },
   { "name": "word", "label": "word to search" }
  ]
 },
 "panels": [
  {
   "title": "Validation logs for specified commit",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", app=~\"$component\"} |~ \"(?i)new commit.*$commit|K8sSynchronization - Schema.*$commit|SchemaErrorPrinter.*$commit\""
    }
   ]
  },
  {
   "title": "Error graph",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate({namespace=\"$namespace\", app=~\"$component\"} |~ \"(?i)Exception|Error\" [$__interval])"
    }
   ]
  },
  {
   "title": "Error Panel",
   "type": "logs",
   "description": "Displays errors and exceptions ",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", app=~\"$component\"} |~ \"(?i)Exception|Error\""
    }
   ]
  },
  {
   "title": "Logs for specified keyword",
   "type": "logs",
   "description": "Search for any word in infra-mgr and/or operator logs in any desired timeframe",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", app=~\"$component\"} |~ \"(?i)$word\""
    }
   ]
  }
 ]
}