{
 "title": "Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "component",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"$namespace\"},label_app)"
    }
   },
   {
    "name": "th2_pin",
    "label": "th2 pin",
    "query": {
     "query": "label_values({__name__=~\"th2_rabbitmq_.*\", namespace=\"$namespace\", job=\"$component\"}, th2_pin)"
    }
   }
  ]
 },
 "panels": [
  { "title": "RabbitMQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RabbitMQ messages in queues",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready{queue=~\"link\\\\[${namespace}:${component}.*\"})",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "Message (outgoing)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Message group rate (outgoing)",
   "type": "graph",
   "description": "This panel shows the quantity of outgoing groups by th2_pin (actual version). For the old version panel shows it without grouping by th2_pin.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(th2_message_group_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[1m])) by (th2_pin)",
     "legendFormat": "{{th2_pin}}"
    },
    {
     "expr": "rate(th2_mq_outgoing_msg_group_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "group (old version)"
    }
   ]
  },
  {
   "title": "Message batch size (outgoing)",
   "type": "graph",
   "description": "This panel shows the ratio of outgoing groups to outgoing group batches by th2_pin (actual version). For the old version panel shows it without grouping by th2_pin.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(th2_message_group_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[1m])) by (th2_pin)\n/\nsum(rate(th2_rabbitmq_message_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"MESSAGE_GROUP\"}[1m])) by (th2_pin)",
     "legendFormat": "{{th2_pin}}"
    },
    {
     "expr": "rate(th2_mq_outgoing_msg_group_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])\n/\nrate(th2_mq_outgoing_msg_group_batch_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "group (old version)"
    }
   ]
  },
  { "title": "Message (incoming)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Message group rate (incoming)",
   "type": "graph",
   "description": "This panel shows the quantity of incoming groups by th2_pin (actual version). For the old version panel shows it without grouping by th2_pin.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(th2_message_group_subscribe_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[1m])) by (th2_pin)",
     "legendFormat": "{{th2_pin}}"
    },
    {
     "expr": "rate(th2_mq_incoming_msg_group_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "group (old version)"
    }
   ]
  },
  {
   "title": "Message batch size (incoming)",
   "type": "graph",
   "description": "This panel shows the ratio of incoming groups to incoming group batches by th2_pin (actual version). For the old version panel shows it without grouping by th2_pin.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(th2_message_group_subscribe_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[1m])) by (th2_pin)\n/\nsum(rate(th2_rabbitmq_message_process_duration_seconds_count{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"MESSAGE_GROUP\"}[1m])) by (th2_pin)",
     "legendFormat": "{{th2_pin}}"
    },
    {
     "expr": "rate(th2_mq_incoming_msg_group_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])\n/\nrate(th2_mq_msg_group_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "group (old version)"
    }
   ]
  },
  {
   "title": "Message group processing time (incoming)",
   "type": "graph",
   "description": "This panel shows the ratio of duration seconds to incoming groups to incoming batches by th2_pin (actual version). For the old version panel shows it without grouping by th2_pin.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum(rate(th2_rabbitmq_message_process_duration_seconds_sum{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"MESSAGE_GROUP\"}[1m])) by (th2_pin)\n/\nsum(rate(th2_message_group_subscribe_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[1m])) by (th2_pin)\n/\nsum(rate(th2_rabbitmq_message_process_duration_seconds_count{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"MESSAGE_GROUP\"}[1m])) by (th2_pin)",
     "legendFormat": "{{th2_pin}}"
    },
    {
     "expr": "rate(th2_mq_msg_group_processing_time_sum{namespace=\"${namespace}\", job=\"${component}\"}[1m])\n/\nrate(th2_mq_incoming_msg_group_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])\n/\nrate(th2_mq_msg_group_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "group (old version)"
    }
   ]
  },
  {
   "title": "Message batch processing time (incoming)",
   "type": "graph",
   "description": "This panel shows the ratio of duration seconds to incoming group batches by th2_pin (actual version). For the old version panel shows it without grouping by th2_pin.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum(rate(th2_rabbitmq_message_process_duration_seconds_sum{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"MESSAGE_GROUP\"}[1m])) by (th2_pin)\r\n/\r\nsum(rate(th2_rabbitmq_message_process_duration_seconds_count{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"MESSAGE_GROUP\"}[1m])) by (th2_pin)\r",
     "legendFormat": "{{th2_pin}}"
    },
    {
     "expr": "rate(th2_mq_msg_group_processing_time_sum{namespace=\"${namespace}\", job=\"${component}\"}[1m])\n/\nrate(th2_mq_msg_group_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "group (old version)"
    }
   ]
  },
  { "title": "Event (outgoing)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Event rate (outgoing)",
   "type": "graph",
   "description": "This panel shows the sum of outgoing events by th2_pin (actual version). For the old version panel shows it without grouping by th2_pin.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(th2_event_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[1m])) by (th2_pin)",
     "legendFormat": "{{th2_pin}}"
    },
    {
     "expr": "sum(th2_event_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}) by (th2_pin)",
     "legendFormat": "avg for the all-time"
    },
    {
     "expr": "rate(th2_mq_outgoing_event_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "avg (1m) (old version)"
    },
    {
     "expr": "th2_mq_outgoing_event_quantity{namespace=\"${namespace}\", job=\"${component}\"}",
     "legendFormat": "avg for the all-time (old version)"
    }
   ]
  },
  {
   "title": "Event batch size (outgoing)",
   "type": "graph",
   "description": "This panel shows the ratio of outgoing events to outgoing event batches by th2_pin (actual version). For the old version panel shows it without grouping by th2_pin.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(th2_event_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[1m])) by (th2_pin)\n/\nsum(rate(th2_rabbitmq_message_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"EVENT\"}[1m])) by (th2_pin)",
     "legendFormat": "{{th2_pin}}"
    },
    {
     "expr": "sum(th2_event_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}) by (th2_pin)\n/\nsum(th2_rabbitmq_message_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"EVENT\"}) by (th2_pin)",
     "legendFormat": "avg for the all-time"
    },
    {
     "expr": "rate(th2_mq_outgoing_event_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])\n/\nrate(th2_mq_outgoing_event_batch_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "avg (1m) (old version)"
    },
    {
     "expr": "th2_mq_outgoing_event_quantity{namespace=\"${namespace}\", job=\"${component}\"}\n/\nth2_mq_outgoing_event_batch_quantity{namespace=\"${namespace}\", job=\"${component}\"}",
     "legendFormat": "avg for the all-time (old version)"
    }
   ]
  },
  { "title": "Event (incoming)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Event processing time (incoming)",
   "type": "graph",
   "description": "This panel shows the ratio of duration seconds to incoming events to incoming event batches by th2_pin (actual version). For the old version panel shows it without grouping by th2_pin.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(th2_rabbitmq_message_process_duration_seconds_sum{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"EVENT\"}[1m])) by (th2_pin)\r\n/\r\nsum(rate(th2_event_subscribe_total{namespace=\"${namespace}\", job=\"${component}\"}[1m])) by (th2_pin)\r\n/\r\nsum(rate(th2_rabbitmq_message_process_duration_seconds_count{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"EVENT\"}[1m]))\r by (th2_pin)",
     "legendFormat": "{{th2_pin}}"
    },
    {
     "expr": "rate(th2_mq_event_processing_time_sum{namespace=\"${namespace}\", job=\"${component}\"}[1m])\n/\nrate(th2_mq_incoming_event_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])\n/\nrate(th2_mq_event_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "{{pod}} (old version)"
    }
   ]
  },
  {
   "title": "Event batch size (incoming)",
   "type": "graph",
   "description": "This panel shows the ratio of incoming events to incoming event batches by th2_pin (actual version). For the old version panel shows it without grouping by th2_pin.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(th2_event_subscribe_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[1m])) by (th2_pin)\n/\nsum(rate(th2_rabbitmq_message_process_duration_seconds_count{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"EVENT\"}[1m])) by (th2_pin)",
     "legendFormat": "avg (1m)"
    },
    {
     "expr": "avg_over_time(th2_event_subscribe_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[$__range])\n/\navg_over_time(th2_rabbitmq_message_process_duration_seconds_count{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"EVENT\"}[$__range])",
     "legendFormat": "avg for the all-time"
    },
    {
     "expr": "rate(th2_mq_incoming_event_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])\n/\nrate(th2_mq_event_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "avg (1m) (old version)"
    },
    {
     "expr": "avg_over_time(th2_mq_incoming_event_quantity{namespace=\"${namespace}\", job=\"${component}\"}[$__range])\n/\navg_over_time(th2_mq_event_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[$__range])",
     "legendFormat": "avg for the all-time (old version)"
    }
   ]
  },
  {
   "title": "Event batch processing time (incoming)",
   "type": "graph",
   "description": "This panel shows the ratio of duration seconds to incoming event batches by th2_pin (actual version). For the old version panel shows it without grouping by th2_pin.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(th2_rabbitmq_message_process_duration_seconds_sum{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"EVENT\"}[1m])) by (th2_pin)\n/\nsum(rate(th2_rabbitmq_message_process_duration_seconds_count{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"EVENT\"}[1m])) by (th2_pin)",
     "legendFormat": "{{th2_pin}}"
    },
    {
     "expr": "rate(th2_mq_event_processing_time_sum{namespace=\"${namespace}\", job=\"${component}\"}[1m])\n/\nrate(th2_mq_event_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "{{pod}} (old version)"
    }
   ]
  }
 ]
}