{
 "title": "Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "component",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"$namespace\"},label_app)"
    }
   },
   {
    "name": "bucket",
    "query": {
     "query": "label_values({__name__=~\".*_processing_time_bucket\", namespace=\"$namespace\", job=\"$component\"}, le)"
    }
   }
  ]
 },
 "panels": [
  { "title": "RabbitMQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RabbitMQ messages in queues",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready{queue=~\"link\\\\[${namespace}:${component}.*\"})",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "Message (outgoing)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Message rate (outgoing)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(th2_mq_outgoing_msg_group_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "group"
    },
    {
     "expr": "rate(th2_mq_outgoing_parsed_msg_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "parsed"
    },
    {
     "expr": "rate(th2_mq_outgoing_raw_msg_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "raw"
    }
   ]
  },
  {
   "title": "Message batch size (outgoing)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(th2_mq_outgoing_msg_group_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m]) / rate(th2_mq_outgoing_msg_group_batch_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "group"
    },
    {
     "expr": "rate(th2_mq_outgoing_parsed_msg_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m]) / rate(th2_mq_outgoing_parsed_msg_batch_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "parsed"
    },
    {
     "expr": "rate(th2_mq_outgoing_raw_msg_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m]) / rate(th2_mq_outgoing_raw_msg_batch_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "raw"
    }
   ]
  },
  { "title": "Message (incoming)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Message rate (incoming)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(th2_mq_incoming_msg_group_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "group"
    },
    {
     "expr": "rate(th2_mq_incoming_parsed_msg_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "parsed"
    },
    {
     "expr": "rate(th2_mq_incoming_raw_msg_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "raw"
    }
   ]
  },
  {
   "title": "Message batch rate (incoming)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(th2_mq_msg_group_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "group"
    },
    {
     "expr": "rate(th2_mq_parsed_msg_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "parsed"
    },
    {
     "expr": "rate(th2_mq_raw_msg_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "raw"
    }
   ]
  },
  {
   "title": "Apdex score of message batch processing time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  sum(rate(th2_mq_msg_group_processing_time_bucket{namespace=\"${namespace}\", job=\"${component}\", le=\"${bucket}\"}[1m])) by (job)\n/\n  sum(rate(th2_mq_msg_group_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[1m])) by (job)"
    }
   ]
  },
  {
   "title": "Message batch size (incoming)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(th2_mq_incoming_msg_group_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m]) / rate(th2_mq_msg_group_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "group"
    },
    {
     "expr": "rate(th2_mq_incoming_parsed_msg_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m]) / rate(th2_mq_parsed_msg_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "parsed"
    },
    {
     "expr": "rate(th2_mq_incoming_raw_msg_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m]) / rate(th2_mq_raw_msg_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "raw"
    }
   ]
  },
  {
   "title": "Message processing time (incoming)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(th2_mq_msg_group_processing_time_sum{namespace=\"${namespace}\", job=\"${component}\"}[1m]) / rate(th2_mq_incoming_msg_group_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m]) / rate(th2_mq_msg_group_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "group"
    },
    {
     "expr": "rate(th2_mq_parsed_msg_processing_time_sum{namespace=\"${namespace}\", job=\"${component}\"}[1m]) / rate(th2_mq_incoming_parsed_msg_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m]) / rate(th2_mq_parsed_msg_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "parsed"
    },
    {
     "expr": "rate(th2_mq_raw_msg_processing_time_sum{namespace=\"${namespace}\", job=\"${component}\"}[1m]) / rate(th2_mq_incoming_raw_msg_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m]) / rate(th2_mq_raw_msg_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "raw"
    }
   ]
  },
  {
   "title": "Message batch processing time (incoming)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(th2_mq_msg_group_processing_time_sum{namespace=\"${namespace}\", job=\"${component}\"}[1m]) / rate(th2_mq_msg_group_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "group"
    },
    {
     "expr": "rate(th2_mq_parsed_msg_processing_time_sum{namespace=\"${namespace}\", job=\"${component}\"}[1m]) / rate(th2_mq_parsed_msg_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "parsed"
    },
    {
     "expr": "rate(th2_mq_raw_msg_processing_time_sum{namespace=\"${namespace}\", job=\"${component}\"}[1m]) / rate(th2_mq_raw_msg_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "raw"
    }
   ]
  },
  { "title": "Event (outgoing)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Event size (outgoing)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(th2_mq_outgoing_event_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "avg (1m)"
    },
    {
     "expr": "th2_mq_outgoing_event_quantity{namespace=\"${namespace}\", job=\"${component}\"}",
     "legendFormat": "avg for the all-time"
    }
   ]
  },
  {
   "title": "Event batch size (outgoing)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(th2_mq_outgoing_event_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m]) / rate(th2_mq_outgoing_event_batch_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "avg (1m)"
    },
    {
     "expr": "th2_mq_outgoing_event_quantity{namespace=\"${namespace}\", job=\"${component}\"} / th2_mq_outgoing_event_batch_quantity{namespace=\"${namespace}\", job=\"${component}\"}",
     "legendFormat": "avg for the all-time"
    }
   ]
  },
  { "title": "Event (incoming)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Apdex score of event batch processing time",
   "type": "graph",
   "description": "https://prometheus.io/docs/practices/histograms/",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  sum(rate(th2_mq_event_processing_time_bucket{namespace=\"${namespace}\", job=\"${component}\", le=\"${bucket}\"}[1m])) by (job)\n/\n  sum(rate(th2_mq_event_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[1m])) by (job)"
    }
   ]
  },
  {
   "title": "Event batch size (incoming)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(th2_mq_incoming_event_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m]) / rate(th2_mq_event_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "avg (1m)"
    }
   ]
  },
  {
   "title": "Event processing time (incoming)",
   "type": "graph",
   "description": "This metric includes processing time from taking messages from MQ to call Cradle for an async storing of event batch and exclude time for storing batch event into Cassandra.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(th2_mq_event_processing_time_sum{namespace=\"${namespace}\", job=\"${component}\"}[1m]) / rate(th2_mq_incoming_event_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m]) / rate(th2_mq_event_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Event batch processing time (incoming)",
   "type": "graph",
   "description": "This metric includes processing time from taking messages from MQ to call Cradle for an async storing of event batch and exclude time for storing batch event into Cassandra.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(th2_mq_event_processing_time_sum{namespace=\"${namespace}\", job=\"${component}\"}[1m]) / rate(th2_mq_event_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}