{
 "title": "Monitoring - new",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "component",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"$namespace\"},label_app)"
    }
   },
   {
    "name": "th2_pin",
    "label": "th2 pin",
    "query": {
     "query": "label_values({__name__=~\"th2_rabbitmq_.*\", namespace=\"$namespace\", job=\"$component\"}, th2_pin)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Box", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Restarts components in pod",
   "type": "graph",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{namespace=\"$namespace\", container=\"$component\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RabbitMQ incoming message rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_queue_messages_published_total{queue=~\"link\\\\[${namespace}:${component}.*\"}[$__rate_interval])) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "RabbitMQ messages in queues",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{queue=~\"link\\\\[${namespace}:${component}.*\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  { "title": "Message statistic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "> Total messages quantity",
   "type": "stat",
   "description": "Shows total message quantity for selected pins about the selected range ",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(th2_message_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"})",
     "legendFormat": "{{message_type}},{{session_alias}}:{{direction}}"
    }
   ]
  },
  {
   "title": "> Total messages quantity per th2 stream",
   "type": "table",
   "description": "Shows total message quantity per th2 message stream for selected pins about the selected range ",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(th2_message_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}) by (message_type,session_alias,direction)",
     "legendFormat": "{{session_alias}}:{{direction}}, {{message_type}}"
    }
   ]
  },
  {
   "title": "> Rate of messages by th2 stream and message kind in items/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(th2_message_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[$__rate_interval]) > 0",
     "legendFormat": "{{session_alias}}:{{direction}}, {{message_type}}"
    }
   ]
  },
  {
   "title": "> Sessions sequence numbers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 1, "x": 23, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "th2_message_group_sequence_publish{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}",
     "legendFormat": "{{session_alias}}:{{direction}}"
    }
   ]
  },
  {
   "title": "< Total messages quantity",
   "type": "stat",
   "description": "Shows total message quantity for selected pins about the selected range ",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(th2_message_subscribe_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"})",
     "legendFormat": "{{message_type}},{{session_alias}}:{{direction}}"
    }
   ]
  },
  {
   "title": "< Total messages quantity per th2 stream",
   "type": "table",
   "description": "Shows total message quantity per th2 message stream for selected pins about the selected range ",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(th2_message_subscribe_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}) by (message_type,session_alias,direction)",
     "legendFormat": "{{session_alias}}:{{direction}}, {{message_type}}"
    }
   ]
  },
  {
   "title": "< Rate of messages by th2 stream and message kind in items/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(th2_message_subscribe_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[$__rate_interval]) > 0",
     "legendFormat": "{{session_alias}}:{{direction}}, {{message_type}}"
    }
   ]
  },
  {
   "title": "< Sessions sequence numbers",
   "type": "table",
   "gridPos": { "h": 7, "w": 1, "x": 23, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "th2_message_group_sequence_subscribe{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}",
     "legendFormat": "{{session_alias}}:{{direction}}"
    }
   ]
  },
  {
   "title": "Message statistic (bytes)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "> Total messages size in bytes",
     "type": "stat",
     "description": "Shows total message size for selected pins about the selected range ",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "expr": "sum(th2_rabbitmq_message_size_publish_bytes{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"MESSAGE_GROUP\"})"
      }
     ]
    },
    {
     "title": "> Total data size per pin",
     "type": "table",
     "description": "Shows total message size per box pin for selected pins about the selected range ",
     "gridPos": { "h": 7, "w": 6, "x": 4, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(th2_rabbitmq_message_size_publish_bytes{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"MESSAGE_GROUP\"}) by (th2_pin)",
       "legendFormat": "{{th2_pin}}"
      }
     ]
    },
    {
     "title": "> Data rate per pin",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 10, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(th2_rabbitmq_message_size_publish_bytes{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"MESSAGE_GROUP\"}[$__rate_interval])) by (th2_pin)",
       "legendFormat": "{{th2_pin}}"
      }
     ]
    },
    {
     "title": "> Size of th2 group in bytes/sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 1, "x": 23, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(th2_rabbitmq_message_size_publish_bytes{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"MESSAGE_GROUP\"}[$__rate_interval])) by (th2_pin)\n/\nsum(rate(th2_message_group_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)",
       "legendFormat": "{{th2_pin}}"
      }
     ]
    },
    {
     "title": "< Total message size in bytes",
     "type": "stat",
     "description": "Shows total message size for selected pins about the selected range ",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "expr": "sum(th2_rabbitmq_message_size_subscribe_bytes{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"MESSAGE_GROUP\"})"
      }
     ]
    },
    {
     "title": "< Total data size per pin",
     "type": "table",
     "description": "Shows total data size per box pin for selected pins about the selected range ",
     "gridPos": { "h": 7, "w": 6, "x": 4, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(th2_rabbitmq_message_size_subscribe_bytes{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}) by (th2_pin)",
       "legendFormat": "{{th2_pin}}"
      }
     ]
    },
    {
     "title": "< Data rate per pin",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 10, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(th2_rabbitmq_message_size_subscribe_bytes{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"MESSAGE_GROUP\"}[$__rate_interval])) by (th2_pin)",
       "legendFormat": "{{th2_pin}}"
      }
     ]
    },
    {
     "title": "< Size of th2 group in bytes/sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 1, "x": 23, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(th2_rabbitmq_message_size_subscribe_bytes{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"MESSAGE_GROUP\"}[$__rate_interval])) by (th2_pin)\n/\nsum(rate(th2_message_group_subscribe_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)",
       "legendFormat": "{{th2_pin}}"
      }
     ]
    }
   ]
  },
  { "title": "Batch/Message size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "> Batch size (messages)",
   "type": "graph",
   "description": "Size of batch in messages sent through th2_pin",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(th2_message_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)\n/\nsum(increase(th2_rabbitmq_message_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_type=\"MESSAGE_GROUP\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)",
     "legendFormat": "{{th2_pin}}"
    }
   ]
  },
  {
   "title": "> Batch size",
   "type": "graph",
   "description": "Size of batch in bytes sent through th2_pin",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(th2_rabbitmq_message_size_publish_bytes{namespace=\"${namespace}\", job=\"${component}\", th2_type=\"MESSAGE_GROUP\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)\n/\nsum(increase(th2_rabbitmq_message_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_type=\"MESSAGE_GROUP\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)",
     "legendFormat": "{{th2_pin}}"
    }
   ]
  },
  {
   "title": "> Message size",
   "type": "graph",
   "description": "Size of message in bytes sent through th2_pin",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(th2_rabbitmq_message_size_publish_bytes{namespace=\"${namespace}\", job=\"${component}\", th2_type=\"MESSAGE_GROUP\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)\n/\nsum(increase(th2_message_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)",
     "legendFormat": "{{th2_pin}}"
    }
   ]
  },
  {
   "title": "< Batch size (messages)",
   "type": "graph",
   "description": "Size of batch in messages received through th2_pin",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(th2_message_subscribe_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)\n/\nsum(increase(th2_rabbitmq_message_process_duration_seconds_count{namespace=\"${namespace}\", th2_type=\"MESSAGE_GROUP\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)",
     "legendFormat": "{{th2_pin}}"
    }
   ]
  },
  {
   "title": "< Batch size",
   "type": "graph",
   "description": "Size of batch in bytes received through th2_pin",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(th2_rabbitmq_message_size_subscribe_bytes{namespace=\"${namespace}\", job=\"${component}\", th2_type=\"MESSAGE_GROUP\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)\n/\nsum(increase(th2_rabbitmq_message_process_duration_seconds_count{namespace=\"${namespace}\", th2_type=\"MESSAGE_GROUP\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)",
     "legendFormat": "{{th2_pin}}"
    }
   ]
  },
  {
   "title": "< Message size",
   "type": "graph",
   "description": "Size of message in bytes received through th2_pin",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(th2_rabbitmq_message_size_subscribe_bytes{namespace=\"${namespace}\", job=\"${component}\", th2_type=\"MESSAGE_GROUP\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)\n/\nsum(increase(th2_message_subscribe_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)",
     "legendFormat": "{{th2_pin}}"
    }
   ]
  },
  {
   "title": "Processing batch",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "batches/sec" }
   ],
   "targets": [
    {
     "expr": "1\n/\n(\nsum(rate(th2_rabbitmq_message_process_duration_seconds_sum{namespace=\"$namespace\", job=\"$component\", th2_type=\"MESSAGE_GROUP\", th2_pin=~\"${th2_pin}\"}[5m])) by (th2_pin)\n/\n  sum(rate(th2_rabbitmq_message_process_duration_seconds_count{namespace=\"$namespace\", job=\"$component\", th2_type=\"MESSAGE_GROUP\", th2_pin=~\"${th2_pin}\"}[5m])) by (th2_pin)\n  )"
    }
   ]
  },
  {
   "title": "Message processing time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "message/sec" }
   ],
   "targets": [
    {
     "expr": "1\n/\n(\n(\n  sum(rate(th2_rabbitmq_message_process_duration_seconds_sum{namespace=\"$namespace\", job=\"$component\", th2_type=\"MESSAGE_GROUP\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)\n/\n  sum(rate(th2_rabbitmq_message_process_duration_seconds_count{namespace=\"$namespace\", job=\"$component\", th2_type=\"MESSAGE_GROUP\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)\n)\n/\n(\nsum(increase(th2_message_subscribe_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)\n/\nsum(increase(th2_rabbitmq_message_process_duration_seconds_count{namespace=\"${namespace}\", th2_type=\"MESSAGE_GROUP\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)\n))"
    }
   ]
  },
  { "title": "Event statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "> Total events quantity",
   "type": "stat",
   "description": "Shows total event quantity for selected pins about the selected range ",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(th2_event_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"})",
     "legendFormat": "{{message_type}},{{session_alias}}:{{direction}}"
    }
   ]
  },
  {
   "title": "> Event batch size",
   "type": "graph",
   "description": "This panel shows the ratio of outgoing events to outgoing event batches by th2_pin (actual version). For the old version panel shows it without grouping by th2_pin.",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(th2_event_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)\n/\nsum(increase(th2_rabbitmq_message_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"EVENT\"}[$__rate_interval])) by (th2_pin)",
     "legendFormat": "{{th2_pin}}"
    }
   ]
  },
  {
   "title": "> Event batch rate",
   "type": "graph",
   "description": "This panel shows the ratio of outgoing events to outgoing event batches by th2_pin (actual version). For the old version panel shows it without grouping by th2_pin.",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(th2_rabbitmq_message_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"EVENT\"}[$__rate_interval])) by (th2_pin)",
     "legendFormat": "{{th2_pin}}"
    }
   ]
  },
  {
   "title": "< Total events quantity",
   "type": "stat",
   "description": "Shows total event quantity for selected pins about the selected range ",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(th2_event_subscribe_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"})"
    }
   ]
  },
  {
   "title": "< Event batch size",
   "type": "graph",
   "description": "This panel shows the ratio of outgoing events to outgoing event batches by th2_pin (actual version). For the old version panel shows it without grouping by th2_pin.",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(th2_event_subscribe_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)\n/\nsum(increase(th2_rabbitmq_message_process_duration_seconds_count{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"EVENT\"}[$__rate_interval])) by (th2_pin)",
     "legendFormat": "{{th2_pin}}"
    }
   ]
  },
  {
   "title": "< Event batch rate",
   "type": "graph",
   "description": "This panel shows the ratio of outgoing events to outgoing event batches by th2_pin (actual version). For the old version panel shows it without grouping by th2_pin.",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(th2_rabbitmq_message_process_duration_seconds_count{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"EVENT\"}[$__rate_interval])) by (th2_pin)",
     "legendFormat": "{{th2_pin}}"
    }
   ]
  },
  {
   "title": "95th percentile of event batch processing rate",
   "type": "graph",
   "description": "Calculates the 95th percentile of event batch processing rate.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(th2_rabbitmq_message_process_duration_seconds_bucket{namespace=\"$namespace\", job=\"$component\", th2_type=\"EVENT\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (le, th2_pin))",
     "legendFormat": "{{th2_pin}}"
    }
   ]
  },
  {
   "title": "Event statistic (bytes)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "> Batch size (events)",
     "type": "graph",
     "description": "Size of batch in messages sent through th2_pin",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(th2_event_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)\n/\nsum(increase(th2_rabbitmq_message_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_type=\"EVENT\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)",
       "legendFormat": "{{th2_pin}}"
      }
     ]
    },
    {
     "title": "> Batch size (bytes)",
     "type": "graph",
     "description": "Size of batch in bytes sent through th2_pin",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(increase(th2_rabbitmq_message_size_publish_bytes{namespace=\"${namespace}\", job=\"${component}\", th2_type=\"EVENT\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)\n/\nsum(increase(th2_rabbitmq_message_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_type=\"EVENT\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)",
       "legendFormat": "{{th2_pin}}"
      }
     ]
    },
    {
     "title": "> Event size (bytes)",
     "type": "graph",
     "description": "Size of message in bytes sent through th2_pin",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(increase(th2_rabbitmq_message_size_publish_bytes{namespace=\"${namespace}\", job=\"${component}\", th2_type=\"EVENT\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)\n/\nsum(increase(th2_event_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)",
       "legendFormat": "{{th2_pin}}"
      }
     ]
    },
    {
     "title": "< Batch size (events)",
     "type": "graph",
     "description": "Size of batch in events received through th2_pin",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(th2_event_subscribe_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)\n/\nsum(increase(th2_rabbitmq_message_process_duration_seconds_count{namespace=\"${namespace}\", th2_type=\"EVENT\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)",
       "legendFormat": "{{th2_pin}}"
      }
     ]
    },
    {
     "title": "< Batch size (bytes)",
     "type": "graph",
     "description": "Size of batch in bytes received through th2_pin",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(increase(th2_rabbitmq_message_size_subscribe_bytes{namespace=\"${namespace}\", job=\"${component}\", th2_type=\"EVENT\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)\n/\nsum(increase(th2_rabbitmq_message_process_duration_seconds_count{namespace=\"${namespace}\", th2_type=\"EVENT\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)",
       "legendFormat": "{{th2_pin}}"
      }
     ]
    },
    {
     "title": "< Event size (bytes)",
     "type": "graph",
     "description": "Size of event in bytes received through th2_pin",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(increase(th2_rabbitmq_message_size_subscribe_bytes{namespace=\"${namespace}\", job=\"${component}\", th2_type=\"EVENT\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)\n/\nsum(increase(th2_event_subscribe_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[$__rate_interval])) by (th2_pin)",
       "legendFormat": "{{th2_pin}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Message (outgoing) ???",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "Message group rate (outgoing) ???",
     "type": "graph",
     "description": "This panel shows the quantity of outgoing groups by th2_pin (actual version). For the old version panel shows it without grouping by th2_pin.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(th2_message_group_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[1m])) by (th2_pin)",
       "legendFormat": "{{th2_pin}}"
      },
      {
       "expr": "rate(th2_mq_outgoing_msg_group_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
       "legendFormat": "group (old version)"
      }
     ]
    },
    {
     "title": "Message batch size (outgoing) ???",
     "type": "graph",
     "description": "This panel shows the ratio of outgoing groups to outgoing group batches by th2_pin (actual version). For the old version panel shows it without grouping by th2_pin.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(th2_message_group_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[1m])) by (th2_pin)\n/\nsum(rate(th2_rabbitmq_message_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"MESSAGE_GROUP\"}[1m])) by (th2_pin)",
       "legendFormat": "{{th2_pin}}"
      },
      {
       "expr": "rate(th2_mq_outgoing_msg_group_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])\n/\nrate(th2_mq_outgoing_msg_group_batch_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
       "legendFormat": "group (old version)"
      }
     ]
    }
   ]
  },
  {
   "title": "Message (incoming) ???",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "Message group rate (incoming) ???",
     "type": "graph",
     "description": "This panel shows the quantity of incoming groups by th2_pin (actual version). For the old version panel shows it without grouping by th2_pin.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(th2_message_group_subscribe_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[1m])) by (th2_pin)",
       "legendFormat": "{{th2_pin}}"
      },
      {
       "expr": "rate(th2_mq_incoming_msg_group_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
       "legendFormat": "group (old version)"
      }
     ]
    },
    {
     "title": "Message batch size (incoming) ???",
     "type": "graph",
     "description": "This panel shows the ratio of incoming groups to incoming group batches by th2_pin (actual version). For the old version panel shows it without grouping by th2_pin.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(th2_message_group_subscribe_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[5m])) by (th2_pin)\n/\nsum(increase(th2_rabbitmq_message_process_duration_seconds_count{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"MESSAGE_GROUP\"}[5m])) by (th2_pin)",
       "legendFormat": "{{th2_pin}}"
      }
     ]
    },
    {
     "title": "Message group processing time (incoming) ???",
     "type": "graph",
     "description": "This panel shows the ratio of duration seconds to incoming groups to incoming batches by th2_pin (actual version). For the old version panel shows it without grouping by th2_pin.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short", "label": "seconds" }
     ],
     "targets": [
      {
       "expr": "sum(rate(th2_rabbitmq_message_process_duration_seconds_sum{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"MESSAGE_GROUP\"}[1m])) by (th2_pin)\n/\nsum(rate(th2_message_group_subscribe_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[1m])) by (th2_pin)\n/\nsum(rate(th2_rabbitmq_message_process_duration_seconds_count{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"MESSAGE_GROUP\"}[1m])) by (th2_pin)",
       "legendFormat": "{{th2_pin}}"
      },
      {
       "expr": "rate(th2_mq_msg_group_processing_time_sum{namespace=\"${namespace}\", job=\"${component}\"}[1m])\n/\nrate(th2_mq_incoming_msg_group_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])\n/\nrate(th2_mq_msg_group_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
       "legendFormat": "group (old version)"
      }
     ]
    },
    {
     "title": "Message batch processing time (incoming) ???",
     "type": "graph",
     "description": "This panel shows the ratio of duration seconds to incoming group batches by th2_pin (actual version). For the old version panel shows it without grouping by th2_pin.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short", "label": "seconds" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(th2_rabbitmq_message_process_duration_seconds_bucket{namespace=\"$namespace\", job=\"$component\"}[1m])) by (le, method, th2_pin))",
       "legendFormat": "{{th2_pin}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Event (outgoing) ???",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Event rate (outgoing)",
     "type": "graph",
     "description": "This panel shows the sum of outgoing events by th2_pin (actual version). For the old version panel shows it without grouping by th2_pin.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(th2_event_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[1m])) by (th2_pin)",
       "legendFormat": "{{th2_pin}}"
      },
      {
       "expr": "sum(th2_event_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}) by (th2_pin)",
       "legendFormat": "avg for the all-time"
      },
      {
       "expr": "rate(th2_mq_outgoing_event_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
       "legendFormat": "avg (1m) (old version)"
      },
      {
       "expr": "th2_mq_outgoing_event_quantity{namespace=\"${namespace}\", job=\"${component}\"}",
       "legendFormat": "avg for the all-time (old version)"
      }
     ]
    },
    {
     "title": "Event batch size (outgoing)",
     "type": "graph",
     "description": "This panel shows the ratio of outgoing events to outgoing event batches by th2_pin (actual version). For the old version panel shows it without grouping by th2_pin.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(th2_event_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[1m])) by (th2_pin)\n/\nsum(rate(th2_rabbitmq_message_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"EVENT\"}[1m])) by (th2_pin)",
       "legendFormat": "{{th2_pin}}"
      },
      {
       "expr": "sum(th2_event_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}) by (th2_pin)\n/\nsum(th2_rabbitmq_message_publish_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"EVENT\"}) by (th2_pin)",
       "legendFormat": "avg for the all-time"
      },
      {
       "expr": "rate(th2_mq_outgoing_event_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])\n/\nrate(th2_mq_outgoing_event_batch_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
       "legendFormat": "avg (1m) (old version)"
      },
      {
       "expr": "th2_mq_outgoing_event_quantity{namespace=\"${namespace}\", job=\"${component}\"}\n/\nth2_mq_outgoing_event_batch_quantity{namespace=\"${namespace}\", job=\"${component}\"}",
       "legendFormat": "avg for the all-time (old version)"
      }
     ]
    }
   ]
  },
  {
   "title": "Event (incoming) ???",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "Event processing time (incoming)",
     "type": "graph",
     "description": "This panel shows the ratio of duration seconds to incoming events to incoming event batches by th2_pin (actual version). For the old version panel shows it without grouping by th2_pin.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(th2_rabbitmq_message_process_duration_seconds_sum{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"EVENT\"}[1m])) by (th2_pin)\r\n/\r\nsum(rate(th2_event_subscribe_total{namespace=\"${namespace}\", job=\"${component}\"}[1m])) by (th2_pin)\r\n/\r\nsum(rate(th2_rabbitmq_message_process_duration_seconds_count{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"EVENT\"}[1m]))\r by (th2_pin)",
       "legendFormat": "{{th2_pin}}"
      },
      {
       "expr": "rate(th2_mq_event_processing_time_sum{namespace=\"${namespace}\", job=\"${component}\"}[1m])\n/\nrate(th2_mq_incoming_event_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])\n/\nrate(th2_mq_event_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
       "legendFormat": "{{pod}} (old version)"
      }
     ]
    },
    {
     "title": "Event batch size (incoming)",
     "type": "graph",
     "description": "This panel shows the ratio of incoming events to incoming event batches by th2_pin (actual version). For the old version panel shows it without grouping by th2_pin.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(th2_event_subscribe_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[1m])) by (th2_pin)\n/\nsum(rate(th2_rabbitmq_message_process_duration_seconds_count{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"EVENT\"}[1m])) by (th2_pin)",
       "legendFormat": "avg (1m)"
      },
      {
       "expr": "avg_over_time(th2_event_subscribe_total{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\"}[$__range])\n/\navg_over_time(th2_rabbitmq_message_process_duration_seconds_count{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"EVENT\"}[$__range])",
       "legendFormat": "avg for the all-time"
      },
      {
       "expr": "rate(th2_mq_incoming_event_quantity{namespace=\"${namespace}\", job=\"${component}\"}[1m])\n/\nrate(th2_mq_event_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
       "legendFormat": "avg (1m) (old version)"
      },
      {
       "expr": "avg_over_time(th2_mq_incoming_event_quantity{namespace=\"${namespace}\", job=\"${component}\"}[$__range])\n/\navg_over_time(th2_mq_event_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[$__range])",
       "legendFormat": "avg for the all-time (old version)"
      }
     ]
    },
    {
     "title": "Event batch processing time (incoming)",
     "type": "graph",
     "description": "This panel shows the ratio of duration seconds to incoming event batches by th2_pin (actual version). For the old version panel shows it without grouping by th2_pin.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(th2_rabbitmq_message_process_duration_seconds_sum{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"EVENT\"}[1m])) by (th2_pin)\n/\nsum(rate(th2_rabbitmq_message_process_duration_seconds_count{namespace=\"${namespace}\", job=\"${component}\", th2_pin=~\"${th2_pin}\", th2_type=\"EVENT\"}[1m])) by (th2_pin)",
       "legendFormat": "{{th2_pin}}"
      },
      {
       "expr": "rate(th2_mq_event_processing_time_sum{namespace=\"${namespace}\", job=\"${component}\"}[1m])\n/\nrate(th2_mq_event_processing_time_count{namespace=\"${namespace}\", job=\"${component}\"}[1m])",
       "legendFormat": "{{pod}} (old version)"
      }
     ]
    }
   ]
  }
 ]
}