{
 "title": "Nodes monitoring",
 "tags": [ "nodes_monitoring" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Nodes status",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum without(container,endpoint,instance,job,namespace,pod) (kube_node_status_condition{status=\"true\"})\nor on (meta)\nsum without(endpoint,job,metrics_path,namespace,service) (label_replace((label_replace(kubelet_node_name,\"instance\",\"$1\",\"instance\",\"(.*):\\\\d+\")), \"meta\",\"0_node_ip\",\"instance\",\".*\")))+1",
     "legendFormat": "{{condition}}|{{node}}|{{meta}}|{{instance}}"
    }
   ]
  },
  {
   "title": "Allocatable memory by nodes (worker nodes)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(kube_node_status_allocatable{resource=\"memory\"}unless on (node) kube_node_spec_taint)* on (node) group_left(instance)label_replace(kubelet_node_name, \"instance\", \"$1\", \"instance\", \"(.*):\\\\d+\")",
     "legendFormat": "{{node}}: "
    }
   ]
  },
  {
   "title": " Total allocatable memory (worker nodes)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    sum by (node) (kube_node_status_allocatable{resource=\"memory\"}) \n    unless on (node)\n    kube_node_spec_taint{key!~\"node.kubernetes.io/.*\", effect=\"NoSchedule\"}    \n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Total memory (master nodes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    sum by (node) (kube_node_status_allocatable{resource=\"memory\"}) \n    and on (node)\n    kube_node_spec_taint{key=\"node-role.kubernetes.io/master\", effect=\"NoSchedule\"}    \n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory usage (master nodes)",
   "type": "gauge",
   "description": "thresholds: \n&#x1F7E1; 80%\n&#x1F534; 90%",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace((1 - (sum by (instance) (node_memory_MemAvailable_bytes) / on (instance)  sum by (instance) (node_memory_MemTotal_bytes))), \"instance\", \"$1\", \"instance\", \"(.*):\\\\d+\") * on (instance) group_left(node) label_replace(kubelet_node_name, \"instance\", \"$1\", \"instance\", \"(.*):\\\\d+\")and on (node) kube_node_spec_taint{key=\"node-role.kubernetes.io/master\", effect=\"NoSchedule\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": " Memory usage (worker nodes)",
   "type": "gauge",
   "description": "thresholds: \n&#x1F7E1; 80%\n&#x1F534; 90%",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n    label_replace(\n        sum by (instance, node) (\n            container_memory_working_set_bytes{container!~\"|POD\", image!=\"\"}\n        ), \"instance\", \"$1\", \"instance\", \"(.*):\\\\d+\"\n    )\n    / on (instance, node)\n    (\n        kube_node_status_allocatable{resource=\"memory\"} \n        * on (node) group_left(instance) \n        label_replace(\n            kubelet_node_name, \"instance\", \"$1\", \"instance\", \"(.*):\\\\d+\"\n        )\n    )\n)\nunless on (node)\nlabel_replace(kube_node_spec_taint{key!~\"node.kubernetes.io/.*\", effect=\"NoSchedule\"}, \"instance\", \"$1\", \"instance\", \"(.*):\\\\d+\")",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Available memory (worker nodes)",
   "type": "stat",
   "description": "thresholds: \n&#x1F7E1; 4Gi\n&#x1F534; 2Gi",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n    (\n        kube_node_status_allocatable{resource=\"memory\"} \n        - on (node)\n        sum by (node) (\n            container_memory_working_set_bytes{container!~\"|POD\", image!=\"\"}\n        )\n    )\n    unless on (node)\n    kube_node_spec_taint{key!~\"node.kubernetes.io/.*\", effect=\"NoSchedule\"}    \n)"
    }
   ]
  },
  {
   "title": "CPU numbers (master nodes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((kube_node_status_capacity{resource=\"cpu\"} and on (node) kube_node_spec_taint{key=\"node-role.kubernetes.io/master\", effect=\"NoSchedule\"}))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": " Memory usage (worker nodes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    label_replace(\n        sum by (instance, node) (\n            container_memory_working_set_bytes{container!~\"|POD\", image!=\"\"}\n        ), \"instance\", \"$1\", \"instance\", \"(.*):\\\\d+\"\n    )\n    / on (instance, node)\n    (\n        kube_node_status_allocatable{resource=\"memory\"} \n        * on (node) group_left(instance) \n        label_replace(\n            kubelet_node_name, \"instance\", \"$1\", \"instance\", \"(.*):\\\\d+\"\n        )\n    )\n)\nunless on (node)\nlabel_replace(kube_node_spec_taint{key!~\"node.kubernetes.io/.*\", effect=\"NoSchedule\"}, \"instance\", \"$1\", \"instance\", \"(.*):\\\\d+\")",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU load (master nodes)",
   "type": "gauge",
   "description": "thresholds: \n&#x1F7E1; 80%\n&#x1F534; 90%",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg((label_replace(avg by (instance) (sum by (instance,cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait\"}[1m]))), \"instance\", \"$1\", \"instance\", \"(.*):\\\\d+\") * on (instance) group_left(node) label_replace(kubelet_node_name, \"instance\", \"$1\", \"instance\", \"(.*):\\\\d+\")) and on (node) kube_node_spec_taint{key=\"node-role.kubernetes.io/master\", effect=\"NoSchedule\"})"
    }
   ]
  },
  {
   "title": "CPU numbers (worker nodes)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(kube_node_status_capacity{resource=\"cpu\"} unless on (node) kube_node_spec_taint)* on (node) group_left(instance)label_replace(kubelet_node_name, \"instance\", \"$1\", \"instance\", \"(.*):\\\\d+\")",
     "legendFormat": "{{node}}: "
    }
   ]
  },
  {
   "title": "Total CPU numbers (worker nodes)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((kube_node_status_capacity{resource=\"cpu\"} \nunless on (node) \nkube_node_spec_taint))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": " CPU usage (worker nodes)",
   "type": "gauge",
   "description": "thresholds: \n&#x1F7E1; 80%\n&#x1F534; 90%",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(label_replace(avg by (instance) (sum by (instance,cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait\"}[1m]))), \"instance\", \"$1\", \"instance\", \"(.*):\\\\d+\") * on (instance) group_left(node) label_replace(kubelet_node_name, \"instance\", \"$1\", \"instance\", \"(.*):\\\\d+\")) unless on (node) kube_node_spec_taint",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Available CPU (worker nodes)",
   "type": "stat",
   "description": "thresholds: \n&#x1F7E1; 4 cores\n&#x1F534; 2 cores",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum((label_replace(sum by (instance) (rate(node_cpu_seconds_total{mode=~\"idle|iowait\"}[1m])), \"instance\", \"$1\", \"instance\", \"(.*):\\\\d+\") * on (instance) group_left(node) label_replace(kubelet_node_name, \"instance\", \"$1\", \"instance\", \"(.*):\\\\d+\")) unless on (node) kube_node_spec_taint)"
    }
   ]
  },
  {
   "title": "Avg CPU load (worker nodes)",
   "type": "stat",
   "description": "thresholds: \n&#x1F7E1; 80%\n&#x1F534; 90%",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg((label_replace(avg by (instance) (sum by (instance,cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait\"}[1m]))), \"instance\", \"$1\", \"instance\", \"(.*):\\\\d+\") * on (instance) group_left(node) label_replace(kubelet_node_name, \"instance\", \"$1\", \"instance\", \"(.*):\\\\d+\")) unless on (node) kube_node_spec_taint)"
    }
   ]
  },
  {
   "title": " CPU usage (worker nodes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(label_replace(avg by (instance) (sum by (instance,cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait\"}[1m]))), \"instance\", \"$1\", \"instance\", \"(.*):\\\\d+\") * on (instance) group_left(node) label_replace(kubelet_node_name, \"instance\", \"$1\", \"instance\", \"(.*):\\\\d+\")) unless on (node) kube_node_spec_taint",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "pods distribution (worker nodes)",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "(kube_node_status_capacity{resource=\"pods\"}or on(node, resource)label_replace(kubelet_running_pod_count, \"resource\", \"pods_deployed\", \"node\", \".*\"))unless on (node) kube_node_spec_taint",
     "legendFormat": "pod_cap|{{node}}|{{resource}}"
    }
   ]
  },
  {
   "title": "FS state",
   "type": "yesoreyeram-boomtable-panel",
   "description": "thresholds: \n&#x1F534; 1Gi",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "label_replace((label_replace(node_filesystem_size_bytes{mountpoint=~ \"/|/opt/.*\"}, \"resource\", \"fs_size\", \"mountpoint\", \".*\")or on(instance, mountpoint, resource)label_replace(node_filesystem_avail_bytes{mountpoint=~ \"/|/opt/.*\"}, \"resource\", \"fs_avail\", \"mountpoint\", \".*\")), \"instance\", \"$1\", \"instance\", \"(.*):\\\\d+\")* on (instance) group_left(node)label_replace(kubelet_node_name, \"instance\", \"$1\", \"instance\", \"(.*):\\\\d+\")",
     "legendFormat": "{{resource}}|{{node}}|{{mountpoint}}"
    }
   ]
  }
 ]
}