---
apiVersion: v2
name: th2
description: th2 service Helm chart

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.8.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 1.0.0

dependencies:
- alias: rabbitmq
  condition: rabbitmq.internal
  #Due to https://github.com/bitnami/charts/issues/10539 the following link next line has been changed from https://charts.bitnami.com/bitnami
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  name: rabbitmq
  version: 8.24.13
- alias: cassandra
  condition: cassandra.internal
  name: cassandra
  version: 5.6.7
- alias: helmoperator
  condition: helmoperator.internal
  repository: https://charts.fluxcd.io
  name: helm-operator
  version: 1.4.2
- alias: jupyterhub
  condition: jupyterhub.custom.internal
  repository: https://jupyterhub.github.io/helm-chart/
  name: jupyterhub
  version: 2.0.0
- alias: dashboard
  condition: dashboard.internal
  repository: https://kubernetes.github.io/dashboard/
  name: kubernetes-dashboard
  version: 5.0.4
