---
apiVersion: v2
name: th2
description: th2 service Helm chart

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 2.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 1.0.0

dependencies:
- alias: rabbitmq
  condition: rabbitmq.internal
  repository: https://charts.bitnami.com/bitnami
  name: rabbitmq
  version: 11.0.3
- alias: cassandra
  condition: cassandra.internal
  repository: https://charts.bitnami.com/bitnami
  name: cassandra
  version: 9.7.3
- alias: dashboard
  condition: dashboard.internal
  repository: https://kubernetes.github.io/dashboard/
  name: kubernetes-dashboard
  version: 5.11.0
- alias: helmController
  condition: helmController.internal
  name: helm-controller
  version: 0.1.0
