---
apiVersion: v1
kind: Service
metadata:
  name: arango-deployment-operator
  namespace: default
  labels:
    app.kubernetes.io/name: kube-arangodb
    helm.sh/chart: kube-arangodb-1.2.20
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: deployment
    release: deployment
spec:
  ports:
    - name: server
      port: 8528
      protocol: TCP
      targetPort: 8528
    - name: http-api
      port: 8628
      protocol: TCP
      targetPort: 8628
    - name: grpc-api
      port: 8728
      protocol: TCP
      targetPort: 8728
  selector:
    app.kubernetes.io/name: kube-arangodb
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: deployment
    release: deployment
    role: leader
  type: ClusterIP