apiVersion: v1
kind: ServiceAccount
metadata:
  name: arango-deployment-operator
  namespace: {{ .Release.Namespace }}
  labels:
      app.kubernetes.io/name: kube-arangodb
      helm.sh/chart: kube-arangodb-1.2.20
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/instance: deployment
      release: deployment
