apiVersion: th2.exactpro.com/v2
kind: Th2Mstore
metadata:
  name: mstore
spec:
  imageName: ghcr.io/th2-net/th2-mstore
  imageVersion: 3.2.0
  extendedSettings:
    envVariables:
      JAVA_TOOL_OPTIONS: -XX:+ExitOnOutOfMemoryError -Ddatastax-java-driver.advanced.connection.init-query-timeout="5000
        milliseconds"
    resources:
      limits:
        cpu: 300m
        memory: 300Mi
      requests:
        cpu: 20m
        memory: 100Mi
    service:
      enabled: false
  disabled: true
