apiVersion: th2.exactpro.com/v2
kind: Th2CoreBox
metadata:
  name: rpt-data-viewer
  annotations:
    e2e: "test-annotation"
spec:
  imageName: ghcr.io/th2-net/th2-rpt-viewer
  imageVersion: 3.1.127
  type: th2-rpt-viewer
  extendedSettings:
    hostAliases:
      - ip: "127.0.0.1"
        hostnames:
          - "test.local"
    service:
      enabled: true
      clusterIP:
        - name: http
          containerPort: 8080
    resources:
      limits:
        cpu: 50m
        memory: 50Mi
      requests:
        cpu: 50m
        memory: 50Mi
