apiVersion: th2.exactpro.com/v1
kind: Th2CoreBox
metadata:
  name: rpt-data-viewer
spec:
  image-name: ghcr.io/th2-net/th2-rpt-viewer
  image-version: 3.1.51
  type: th2-rpt-viewer
  extended-settings:
    service:
      enabled: true
      type: ClusterIP
      endpoints:
        - name: 'gui'
          targetPort: 8080
    resources:
      limits:
        memory: 50Mi
        cpu: 50m
      requests:
        memory: 50Mi
        cpu: 50m
#      mounitng:
#        TBD
