apiVersion: th2.exactpro.com/v1
kind: Th2CoreBox
metadata:
  name: rpt-data-viewer
spec:
  image-name: ghcr.io/th2-net/th2-rpt-viewer
  image-version: 3.1.127
  type: th2-rpt-viewer
  extended-settings:
    hostAliases:
    - ip: "127.0.0.1"
      hostnames: 
      - "test.local"
    service:
      enabled: true
      type: ClusterIP
      endpoints:
        - name: "gui"
          targetPort: 8080
    resources:
      requests:
        memory: 50Mi
        cpu: 50m
