---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jupyterhub-shared-volume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: cstor-csi-disk