apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-mgr
data:
  config.yml: |
    git:
      remoteRepository: {{ .Values.infraMgr.git.repository }}
      localRepositoryRoot: {{ .Values.infraMgr.git.repositoryLocalCache }}
      privateKeyFile: {{ .Values.infraMgr.git.secretMountPath }}/{{ .Values.infraMgr.git.privateKeyFileSecret }}
      ignoreInsecureHosts: true

    rabbitmq:
      vhostPrefix: {{ .Values.infraMgr.rabbitmq.vHostPrefix }}

    cassandra:
      password: "${CASSANDRA_PASSWORD}"
      keyspacePrefix: {{ .Values.infraMgr.cassandra.keyspacePrefix }}

    kubernetes:
      useCustomConfig: false
      namespacePrefix: {{ .Values.infraMgr.kubernetes.namespacePrefix }}

      ingress: {{ .Values.infraMgr.kubernetes.ingress }}

{{- with .Values.infraMgr.kubernetes.secrets }}
      secretNames:
{{- toYaml . | nindent 8 }}
{{- end }}

{{- with .Values.infraMgr.kubernetes.configMaps }}
      configMaps:
{{- toYaml . | nindent 8 }}
{{- end }}
