apiVersion: v1
kind: Service
metadata:
  name: git-ssh
spec:
  selector:
    app: git-ssh
  type: NodePort
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: {{ .Values.port | default 32600 }}

