apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: components
 namespace: <namespace>
spec:
 accessModes:
   - ReadWriteMany
 volumeMode: Filesystem
 resources:
   requests:
     storage: 10Gi
 storageClassName: local-storage
