apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infra-operator
  annotations:
  {{- include "common-annotations" . | nindent 4  }}
rules:
  - apiGroups:
      - ""
      - th2.exactpro.com
      - helm.fluxcd.io
      - apiextensions.k8s.io
    resources: 
      - configmaps
      - secrets
      - th2boxes
      - th2coreboxes
      - th2dictionaries
      - th2estores
      - th2links
      - th2mstores
      - helmreleases
      - namespaces
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infra-mgr
  annotations:
  {{- include "common-annotations" . | nindent 4  }}
rules:
  - apiGroups:
      - th2.exactpro.com
      - ""
      - apps
      - networking.k8s.io
    resources: 
      - configmaps
      - secrets
      - pods 
      - deployments
      - th2boxes
      - th2coreboxes
      - th2dictionaries
      - th2estores
      - th2links
      - th2mstores
      - ingresses
    verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-operator-service
  annotations:
  {{- include "common-annotations" . | nindent 4  }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-mgr
  annotations:
  {{- include "common-annotations" . | nindent 4  }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: infra-operator-binding
  annotations:
  {{- include "common-annotations" . | nindent 4  }}
roleRef:
  kind: ClusterRole
  name: infra-operator
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: infra-operator-service
    namespace: {{ .Release.Namespace }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: infra-mgr-binding
  annotations:
  {{- include "common-annotations" . | nindent 4  }}
roleRef:
  kind: ClusterRole
  name: infra-mgr
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: infra-mgr
    namespace: {{ .Release.Namespace }}
