apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infra-operator
  annotations:
  {{- include "common-annotations" . | nindent 4  }}
rules:
  - apiGroups:
      - ""
      - apps
      - networking.k8s.io
      - extensions
      - th2.exactpro.com
      - helm.fluxcd.io
      - apiextensions.k8s.io
    resources:
      - "*"
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infra-mgr
  annotations:
  {{- include "common-annotations" . | nindent 4  }}
rules:
  - apiGroups:
      - ""
      - apps
    resources:
      - "*"
    verbs: ["get", "watch", "list"]
  - apiGroups:
      - th2.exactpro.com
      - ""
      - apps
    resources: ["configmaps", "secrets", "pods", "customresourcedefinitions", "deployments"]
    verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-operator-service
  annotations:
  {{- include "common-annotations" . | nindent 4  }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-mgr
  annotations:
  {{- include "common-annotations" . | nindent 4  }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: infra-operator-binding
  annotations:
  {{- include "common-annotations" . | nindent 4  }}
roleRef:
  kind: ClusterRole
  name: infra-operator
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: infra-operator-service
    namespace: {{ .Release.Namespace }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: infra-mgr-binding
  annotations:
  {{- include "common-annotations" . | nindent 4  }}
roleRef:
  kind: ClusterRole
  name: infra-mgr
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: infra-mgr
    namespace: {{ .Release.Namespace }}
