{{/*
  Generating svc for converter for k8
  */}}
apiVersion: v1
kind: Service
metadata:
  name: converter
  annotations:
  {{- include "common-annotations" . | nindent 4 }}
  labels:
    app: converter
    {{- if .Values.converter.prometheusConfiguration.enabled }}
    monitoring-pod: "true"
    {{- end }}
spec:
  type: ClusterIP
  selector:
    app: converter
  ports:
    - name: default
      protocol: TCP
      port: 8080
      targetPort: 8080
{{- if .Values.converter.prometheusConfiguration.enabled }}
  {{- include "svc-prometheus-port" .Values }}
{{- end }}
