{{- if .Values.infraGit.internal }}
---
apiVersion: v1
kind: Service
metadata:
  name: infra-git
spec:
  selector:
    app: infra-git
  type: NodePort
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: {{ .Values.infraGit.nodePort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: infra-git
    {{ include "th2-labels" . }}
  name: infra-git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-git
  template:
    metadata:
      labels:
        app: infra-git
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - image: "{{ .Values.infraGit.image.repository }}:{{ .Values.infraGit.image.tag }}"
        name: infra-git
        volumeMounts:
          - name: repos-volume
            mountPath: /home/git/repo/
          - name: keys
            mountPath: /opt/keys/
        command:
        - "/bin/bash"
        - "-c"
        - |
          set -ex
          mkdir /home/git/.ssh
          cp /opt/keys/authorized_keys /home/git/.ssh/authorized_keys
          ls -lah /home/git/repo
          /usr/sbin/sshd -D -e
        livenessProbe:
          tcpSocket:
            port: 22
          initialDelaySeconds: 40
          periodSeconds: 20
        resources:
{{ toYaml .Values.infraGit.resources | indent 10 }}
      volumes:
        - name: repos-volume
          persistentVolumeClaim:
            claimName: repos-volume
        - name: keys
          configMap:
            name: keys-repo
      imagePullSecrets:
      {{- include "imagePullSecret" .Values.registries | trim | nindent 6 }}
  revisionHistoryLimit: 2
---
{{ if .Values.infraGit.pvc.enable}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repos-volume
spec:
{{- if .Values.infraGit.pvc.existingVolume }}
  volumeName: {{ .Values.infraGit.pvc.existingVolume }}
{{- end }}
  accessModes:
    - {{ .Values.infraGit.pvc.accessModes }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.infraGit.pvc.storage }}
  storageClassName: {{ .Values.infraGit.pvc.storageClassName }}
{{ end }}  
---
{{- end }}
