---
apiVersion: v1
kind: Service
metadata:
  name: infra-repo
  annotations:
  {{- include "common-annotations" . | nindent 4  }}
spec:
  selector:
    app: infra-repo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: infra-repo
    {{ include "th2-labels" . }}
  name: infra-repo
  annotations:
  {{- include "common-annotations" . | nindent 4  }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-repo
  template:
    metadata:
      labels:
        app: infra-repo
    spec:
      containers:
        - name: infra-repo
          image: "{{ .Values.infraRepo.image.repository }}:{{ .Values.infraRepo.image.tag }}"
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 20
      imagePullSecrets:
      {{- include "imagePullSecret" .Values.registries | trim | nindent 6 }}
  revisionHistoryLimit: 2
