---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- include "ingress-annotations" . | nindent 4  }}
    {{- include "common-annotations" . | nindent 4  }}
  name: th2-root
spec:
  defaultBackend:
    service:
      name: infra-repo
      port:
        number: 8080
  {{ if .Values.ingress.ingressClass }}
  ingressClassName: "{{ .Values.ingress.ingressClass }}"
  {{- end }}
  rules:
  {{- if .Values.ingress.infraHost }}
  - host: "{{ .Values.ingress.infraHost }}"
    http:
  {{- else if .Values.ingress.host }}
  - host: "{{ .Values.ingress.host }}"
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: infra-repo
            port:
              number: 8080

