---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    {{- include "ingress-annotations" . | nindent 4  }}
    {{- include "common-annotations" . | nindent 4  }}
  name: ingress-service
spec:
  rules:
  {{- if .Values.ingress.host }}
  - host: "{{ .Values.ingress.host -}}"
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
      - backend:
          serviceName: infra-editor
          servicePort: 8080
        path: /editor($|/.*)   
      {{- if .Values.infraEditorV2.enabled }}      
      - backend:
          serviceName: infra-editor-v2
          servicePort: 8080
        path: /editor-2($|/.*)
      - backend:
          serviceName: infra-mgr
          servicePort: 8080
        path: /editor-2/backend/(.*)
      {{- end }}
      - backend:
          serviceName: infra-mgr
          servicePort: 8080
        path: /editor/backend/(.*)