---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- include "ingress-annotations" . | nindent 4  }}
    {{- include "common-annotations" . | nindent 4  }}
  name: ingress-service
spec:
  ingressClassName: "{{ .Values.ingress.ingressClass }}"
  rules:
  {{- if .Values.ingress.host }}
  - host: "{{ .Values.ingress.host -}}"
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
      - path: /editor($|/.*)
        pathType: Prefix
        backend:
          service:
            name: infra-editor
            port:
              number: 8080
      - path: /editor/backend/(.*)
        pathType: Prefix
        backend:
          service:
            name: infra-mgr
            port:
              number: 8080
      {{- if .Values.infraEditorV2.enabled }}
      - backend:
          service:
            name: infra-editor-v2
            port:
              number: 8080
        path: /editor-2($|/.*)
        pathType: Prefix
      {{- end }}
