---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    {{- include "ingress-annotations" . | nindent 4  }}
    {{- include "common-annotations" . | nindent 4  }}
  name: ingress-service
spec:
  rules:
  {{- if .Values.ingress.host }}
  - host: "{{ .Values.ingress.host -}}"
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
      {{- if eq .Values.infraEditor.enabled true}}
      - backend:
          serviceName: infra-editor
          servicePort: 8080
        path: /editor($|/.*)
      {{- end }}
      
      {{- if eq .Values.infraEditorV2.enabled true}}      
      - backend:
          serviceName: infra-editor-v2
          servicePort: 8080
        path: /editor($|/.*)
      {{- end }}
      - backend:
          serviceName: infra-mgr
          servicePort: 8080
        path: /editor/backend/(.*)
