---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- if .Values.ingress.annotations.infraNamespace }}
    {{- toYaml .Values.ingress.annotations.infraNamespace | nindent 4  }}
    {{- end -}}
    {{- include "common-annotations" . | nindent 4  }}
  name: ingress-service
spec:
  {{ if .Values.ingress.ingressClass }}
  ingressClassName: "{{ .Values.ingress.ingressClass }}"
  {{- end }}
  rules:
  {{- if .Values.ingress.infraHost }}
  - host: "{{ .Values.ingress.infraHost }}"
    http:
  {{- else if .Values.ingress.host }}
  - host: "{{ .Values.ingress.host }}"
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
      - path: /editor{{ ternary "/" "($|/.*)" $.Values.openshift.enabled }}
        pathType: Prefix
        backend:
          service:
            name: infra-editor
            port:
              number: 8080
      - path: /editor/backend/{{ ternary "" "(.*)" $.Values.openshift.enabled }}
        pathType: Prefix
        backend:
          service:
            name: infra-mgr
            port:
              number: 8080
      {{- if .Values.infraEditorV2.enabled }}
      - path: /editor-2{{ ternary "/" "($|/.*)" $.Values.openshift.enabled }}
        pathType: Prefix
        backend:
          service:
            name: infra-editor-v2
            port:
              number: 8080
      - path: /editor-2/backend/{{ ternary "" "(.*)" $.Values.openshift.enabled }}
        pathType: Prefix
        backend:
          service:
            name: infra-mgr
            port:
              number: 8080
      {{- end }}
