
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infra-mgr
  annotations:
  {{- include "common-annotations" . | nindent 4  }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - namespaces
      - services
      - pods
    verbs: ["*"]
  - apiGroups:
      - th2.exactpro.com
    resources: ["*"]
    verbs: ["*"]
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs: ["*"]
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs: ["*"]
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs: ["*"]
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-mgr-service
  annotations:
  {{- include "common-annotations" . | nindent 4  }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: infra-mgr-binding
  annotations:
  {{- include "common-annotations" . | nindent 4  }}
roleRef:
  kind: ClusterRole
  name: infra-mgr
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: infra-mgr-service
    namespace: {{ .Release.Namespace }}
---
