{{- if not .Values.git.ssh.secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helm-operator.fullname" . }}-git-deploy
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end -}}
