{{- if and .Values.git.config.enabled .Values.git.config.createSecret  -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "git.config.secretName" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  gitconfig: {{ .Values.git.config.data | b64enc }}
{{- end -}}
