---
commonAnnotations: {}
component:
  ingress:
    host:
    annotations:
      default: {}
      extra: {}
  secrets:
    rabbitMQ: rabbitMQ
    cassandra: cassandra
  image:
  name: comp1
  extendedSettings:
    service:
      enabled: false
      ingress:
        urlPaths: []
    resources:
      limits:
        memory: 200Mi
        cpu: 200m
        ephemeral-storage: "1Gi"
      requests:
        memory: 100Mi
        cpu: 50m
        ephemeral-storage: "1Gi"
    replicas: 1
  prometheus:
    enabled: false
  logging:
    checksum: loggingchecksum
    config:
  cradleManager:
    checksum: cradleMangerchecksum
    config:
  mqRouter:
    checksum: mqchecksum
    config:
  grpcRouter:
    checksum: grpcchecksum
    config:
  custom:
    # prod:
    #   value: dskgfsdgf
    # test:
    #   value: example
  mq:
    # sprod:
    #   value: 2222
  grpc:
    # sprod:
    #   value: 3333
  dictionaries:
    # - name: FIX5-0
    #   type: SINGLE
    #   data: ABC
    # - name: FIX
    #   type: LEVEL1
    #   data: XYZ
