---
commonAnnotations: {}
openshift:
  enabled: false
component:
  runAsJob: false
  bookConfig:
    bookName: defaultBook
  ingress:
    host:
    annotations:
      default: {}
      extra: {}
  secrets:
    rabbitMQ: rabbitMQ
    cassandra: cassandra
  image:
  name: comp1
  securityContext:
    runAsUser: 65635
    runAsGroup: 65635
  extendedSettings:
    parallelism: 1
    completions: 1
    externalBox:
      enabled: false
    service:
      enabled: false
      clusterIP: []
      ingress:
        urlPaths: []
    resources:
      limits:
        memory: 200Mi
        ephemeral-storage: "1Gi"
      requests:
        memory: 100Mi
        cpu: 50m
        ephemeral-storage: "1Gi"
    replicas: 1
  prometheus:
    enabled: false
  logging:
    checksum: loggingchecksum
    config:
  cradleManager:
    checksum: cradleMangerchecksum
    config:
  mqRouter:
    checksum: mqchecksum
    config:
  grpcRouter:
    checksum: grpcchecksum
    config:
  custom:
    # prod:
    #   value: dskgfsdgf
    # test:
    #   value: example
  mq:
    # sprod:
    #   value: 2222
  grpc:
    # sprod:
    #   value: 3333
  dictionaries: {}
