{{/*
Generating svc for infra-mgr for k8
*/}}
{{- define "infra-mgr-service" }}
apiVersion: v1
kind: Service
metadata:
  name: infra-mgr
  labels:
    app: infra-mgr
    {{- if .infraMgr.prometheusConfiguration.enabled }}
    monitoring-pod: "true"
    {{- end }}
spec:
  type: ClusterIP
  selector:
    app: infra-mgr
  ports:
    - name: default
      protocol: TCP
      port: 8080
      targetPort: default
{{- if .infraMgr.prometheusConfiguration.enabled }}
    {{- include "svc-prometheus-port" .Values }}
{{- end }}
{{- end }}
