{{- if .Values.git-ssh.internal true }}
---
apiVersion: v1
kind: Service
metadata:
  name: git-ssh
spec:
  selector:
    app: git-ssh
  type: NodePort
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: {{ .Values.git-ssh.port | default 32600 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: git-ssh
  name: git-ssh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-ssh
  template:
    metadata:
      labels:
        app: git-ssh
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - image: ghcr.io/th2-net/git-ssh:v0.1.0
          name: git-ssh
          volumeMounts:
            - name: repos-volume
              mountPath: /home/git/repo/
            - name: keys
              mountPath: /home/keys/
          livenessProbe:
            tcpSocket:
              port: 22
            initialDelaySeconds: 40
            periodSeconds: 20
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "mkdir /home/git/.ssh && cp /home/keys/git_keys /home/git/.ssh/authorized_keys && chown -R 1000:1000 /home/git/.ssh/ && /usr/sbin/sshd -D",
            ]
      volumes:
        - name: repos-volume
          persistentVolumeClaim:
            claimName: repos-volume
        - name: keys
          configMap:
            name: keys-repo
      imagePullSecrets:
        - name: th2-core
  revisionHistoryLimit: 2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: repos-volume
  labels:
    app: repos-volume
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /opt/git
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.git-ssh.node }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repos-volume
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      app: repos-volume
---
{{- end }}
