---
apiVersion: v1
kind: Service
metadata:
  name: infra-editor
spec:
  selector:
    app: infra-editor
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: infra-editor
  name: infra-editor
  annotations:
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-editor
  template:
    metadata:
      labels:
        app: infra-editor
    spec:
      containers:
      - image: {{ .Values.infraEditor.image.repository }}:{{ .Values.infraEditor.image.tag }}
        name: infra-editor
        resources:
          limits:
            memory: 100Mi
            cpu: 100m
          requests:
            memory: 50Mi
            cpu: 100m
        envFrom:
        volumeMounts:
        - name: logging-volume
          mountPath: /home/etc/log4j.properties
          subPath: log4j.properties
      volumes:
      - name: logging-volume
        configMap:
          name: java-logging-config
      imagePullSecrets:
      - name: th2-core
  revisionHistoryLimit: 2
