{{ include "infraOperator-config" . }}
---
{{ include "infra-operator-service" .Values }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-operator
  labels:
    app: infra-operator
    {{ include "th2-labels" . }}
spec:
  selector:
    matchLabels:
      app: infra-operator
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include "infraOperator-config" . | sha256sum }}
      labels:
        app: infra-operator
    spec:
      imagePullSecrets:
      - name: th2-core
      serviceAccountName: infra-operator-service
      initContainers:
      - name: init-myservice
        image: busybox:1.30.1
        command: ['sh', '-c',
          'until nc -vz rabbitmq 5672; do echo "Waiting for rabbitmq service"; sleep 2; done;']
      containers:
      - name: infra-operator
        image: "{{ .Values.infraOperator.image.repository }}:{{ .Values.infraOperator.image.tag }}"
        {{- if .Values.infraOperator.prometheusConfiguration.enabled }}
        ports:
        - name: metrics
          containerPort: {{ default 9752 .Values.infraOperator.prometheusConfiguration.port }}
        {{- end }}
        resources:
{{ toYaml .Values.infraOperator.resources | indent 10 }}
        volumeMounts:
          - name: configs
            mountPath: /var/th2/config/
        env:
        {{- if .Values.infraOperator.jvm.javaToolOptions }}
        - name: JAVA_TOOL_OPTIONS
          value: {{ .Values.infraOperator.jvm.javaToolOptions | quote }}
        {{- end }}
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              {{- if .Values.rabbitmq }}
              {{- if .Values.rabbitmq.fullnameOverride }}
              name: {{ .Values.rabbitmq.fullnameOverride }}
              {{- else }}
              name: rabbitmq
              {{- end }}
              {{- else }}
              name: rabbitmq
              {{- end }}
              key: rabbitmq-password
      volumes:
        - name: configs
          projected:
            sources:
            - configMap:
                name: logging-config
            - configMap: 
                name: infra-operator
