{{ include "infraMgr-config" . }}
---
{{ include "infra-mgr-service" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-mgr
  annotations:
  {{- include "common-annotations" . | nindent 4  }}
  labels:
    app: infra-mgr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-mgr
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include "infraMgr-config" . | sha256sum }}
      labels:
        app: infra-mgr
    spec:
      imagePullSecrets:
      - name: th2-core
      serviceAccountName: infra-mgr-service
      containers:
      - name: infra-mgr
        image: "{{ .Values.infraMgr.image.repository }}:{{ .Values.infraMgr.image.tag }}"
        ports:
        - name: default
          containerPort: 8080
        {{- if .Values.infraMgr.prometheusConfiguration.enabled }}
        - name: metrics
          containerPort: {{ default 9752 .Values.infraMgr.prometheusConfiguration.port }}
        {{- end }}
        resources:
          limits:
            cpu: 200m
            memory: 1000Mi
          requests:
            cpu: 20m
            memory: 300Mi
        volumeMounts:
          - name: configs
            mountPath: /home/service/config/
          - name: secrets
            readOnly: true
            mountPath: {{ .Values.infraMgr.git.secretMountPath }}
        env:
          - name: JAVA_TOOL_OPTIONS
            value: -XX:MaxHeapSize=2048m
          - name: HTTPS_AUTH_USERNAME 
            valueFrom:
              secretKeyRef:
                name: th2-git-access-schemas
                key: httpAuthUsername
          - name: HTTPS_AUTH_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: th2-git-access-schemas
                key: httpAuthPassword
      volumes:
      - name : secrets
        secret:
          secretName: {{ .Values.infraMgr.git.secretName }}
      - name: configs
        projected:
          sources:
          - configMap:
              name: logging-config
          - configMap:
              name: infra-mgr
