apiVersion: v1
kind: Service
metadata:
  name: infra-mgr
spec:
  type: NodePort
  selector:
    app: infra-mgr
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-mgr
  labels:
    app: infra-mgr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-mgr
  template:
    metadata:
      labels:
        app: infra-mgr
    spec:
      imagePullSecrets:
        - name: th2-core
        - name: th2-solution
      serviceAccountName: infra-mgr-service
      containers:
      - name: infra-mgr
        image: "{{ .Values.infraMgr.image.repository }}:{{ .Values.infraMgr.image.tag }}"
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: configs
            mountPath: /home/service/config/
          - name: secrets
            readOnly: true
            mountPath: {{ .Values.infraMgr.git.secretMountPath }}
        env:
      volumes:
      - name : secrets
        secret:
          secretName: {{ .Values.infraMgr.git.secretName }}
      - name: configs
        projected:
          sources:
          - configMap:
              name: java-logging-config
          - configMap:
              name: infra-mgr
