{{ include "infraMgr-config" . }}
---
{{ include "infra-mgr-service" .Values }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-mgr
  labels:
    app: infra-mgr
    {{ include "th2-labels" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-mgr
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include "infraMgr-config" . | sha256sum }}
      labels:
        app: infra-mgr
    spec:
      imagePullSecrets:
      - name: th2-core
      serviceAccountName: infra-mgr-service
      initContainers:
      - name: init-myservice
        image: busybox:1.30.1
        command: ['sh', '-c',
          'until nc -vz infra-git 22; do echo "Waiting for infra-git service"; sleep 2; done;']
      containers:
      - name: infra-mgr
        image: "{{ .Values.infraMgr.image.repository }}:{{ .Values.infraMgr.image.tag }}"
        ports:
        - name: default
          containerPort: 8080
        {{- if .Values.infraMgr.prometheusConfiguration.enabled }}
        - name: metrics
          containerPort: {{ default 9752 .Values.infraMgr.prometheusConfiguration.port }}
        {{- end }}
        resources:
{{ toYaml .Values.infraMgr.resources | indent 10 }}
        volumeMounts:
          - name: configs
            mountPath: /home/service/config/
          - name: secrets
            readOnly: true
            mountPath: {{ .Values.infraMgr.git.secretMountPath }}
        env:
          - name: HOME 
            value: /home/service/
          {{- if .Values.infraMgr.jvm.javaToolOptions }}
          - name: JAVA_TOOL_OPTIONS
            value: {{ .Values.infraMgr.jvm.javaToolOptions | quote }}
          {{- end }}
          - name: HTTPS_AUTH_USERNAME 
            valueFrom:
              secretKeyRef:
                name: th2-git-access-schemas
                key: httpAuthUsername
          - name: HTTPS_AUTH_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: th2-git-access-schemas
                key: httpAuthPassword
          - name: CASSANDRA_PASS
            valueFrom:
              secretKeyRef:
                name: {{ default .Values.infraMgr.cassandra.secret .Values.cassandra.fullnameOverride }}
                key: cassandra-password
      volumes:
      - name : secrets
        secret:
          secretName: {{ .Values.infraMgr.git.secretName }}
      - name: configs
        projected:
          sources:
          - configMap:
              name: logging-config
          - configMap:
              name: infra-mgr
