---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    {{- if .Values.ingress.annotations.default }}
    {{- toYaml $.Values.ingress.annotations.default | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.annotations.extra }}
    {{- toYaml $.Values.ingress.annotations.extra | nindent 4 }}
    {{- end }}
  name: ingress-service
spec:
  rules:
  {{- if .Values.ingress.host }}
  - host: "{{ .Values.ingress.host -}}"
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
      - backend:
          serviceName: infra-editor
          servicePort: 8080
        path: /editor/(.*)
      - backend:
          serviceName: infra-mgr
          servicePort: 8080
        path: /editor/backend/(.*)
      - backend:
          {{- if not .Values.rabbitmq.fullnameOverride }}
          serviceName: rabbitmq-discovery
          {{- else }}
          serviceName: {{ .Values.rabbitmq.fullnameOverride }}
          {{- end }}
          servicePort: 15672
        path: /rabbitmq/(.*)
