---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    {{- include "ingress-annotaitions" . | nindent 4  }}
  name: ingress-service
spec:
  rules:
  {{- if .Values.ingress.host }}
  - host: "{{ .Values.ingress.host -}}"
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
      - backend:
          serviceName: infra-editor
          servicePort: 8080
        path: /editor/(.*)
      - backend:
          serviceName: infra-mgr
          servicePort: 8080
        path: /editor/backend/(.*)

