---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/([a-z\-0-9]*)$ $scheme://$http_host/$1/ redirect;
      if ($request_uri ~ "^/rabbitmq($|/.*)") {
        proxy_pass http://upstream_balancer$1;
        break;
      }
  name: ingress-service
spec:
  rules:
  {{- if .Values.ingress.host }}
  - host: "{{ .Values.ingress.host -}}"
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
      - backend:
          serviceName: infra-editor
          servicePort: 8080
        path: /editor($|/.*)
      - backend:
          serviceName: infra-mgr
          servicePort: 8080
        path: /editor/backend/(.*)
      - backend:
          {{- if not .Values.rabbitmq.fullnameOverride }}
          serviceName: rabbitmq-discovery
          {{- else }}
          serviceName: {{ .Values.rabbitmq.fullnameOverride }}
          {{- end }}
          servicePort: 15672
        path: /rabbitmq($|/.*)
