---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    {{- if .Values.ingress.annotations.default }}
    {{- toYaml $.Values.ingress.annotations.default | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.annotations.extra }}
    {{- toYaml $.Values.ingress.annotations.extra | nindent 4 }}
    {{- end }}
  name: ingress-rules
spec:
  rules:
  {{- if .Values.ingress.host }}
  - host: "{{ .Values.ingress.host -}}"
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
      - path: /${SCHEMA_NAMESPACE}/backend/(.*)
        backend:
          serviceName: rpt-data-provider
          servicePort: 8080
      - path: /${SCHEMA_NAMESPACE}/(.*)
        backend:
          serviceName: rpt-data-viewer
          servicePort: 8080
