{{- if .Values.prometheus.operator.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pods-monitoring
  annotations:
  {{- include "common-annotaitions" . | nindent 4  }}
  namespace: {{ .Values.prometheus.operator.serviceMonitor.namespace }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      monitoring-pod: "true"
  endpoints:
  - port: metrics
    interval: 10s
  namespaceSelector:
    any: true
{{ end }}