{{ if and .Values.rabbitmq.prometheus.operator.enabled .Values.rabbitmq.prometheus.operator.alerts.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: prometheusRule
metadata:
  name: prometheusRule
  annotations:
  {{- include "common-annotations" . | nindent 4  }}
  namespace: {{ .Values.rabbitmq.prometheus.operator.serviceMonitor.namespace }}
  labels:
    release: prometheus
spec:
  - name: rabbitmq
    groups:
      - name: th2.rules
        rules:
          - alert: RabbitmqTooMuchMessages
            expr: rabbitmq_queue_messages_ready > 100000
            for: 2m
            labels:
              severity: high
              team: devops
            annotations:
              summary: |-
                Rabbitmq has more than 100000 messages in a queue
              description: |-
                Queue {{ $labels.queue }}: {{ $value }}
{{ end }}