annotations:
  category: Database
apiVersion: v2
appVersion: 4.0.7
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x.x
description: Apache Cassandra is an open source distributed database management system
  designed to handle large amounts of data across many servers, providing high availability
  with no single point of failure.
home: https://github.com/bitnami/charts/tree/main/bitnami/cassandra
icon: https://bitnami.com/assets/stacks/cassandra/img/cassandra-stack-220x234.png
keywords:
- cassandra
- database
- nosql
maintainers:
- name: Bitnami
  url: https://github.com/bitnami/charts
name: cassandra
sources:
- https://github.com/bitnami/containers/tree/main/bitnami/cassandra
- http://cassandra.apache.org
version: 9.7.3
