apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  destination:
    namespace: argo-service
    server: "https://kubernetes.default.svc"
  project: default
  sources:
  - repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.9.0
    helm:
      valueFiles:
      - $values/argocd/openshift/sealed-secrets/values.yaml
  - repoURL: https://github.com/th2-net/th2-infra.git
    targetRevision: master
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-crd-clusterrole
spec:
  destination:
    namespace: argo-service
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: false
    path: argocd/openshift/sealed-secrets/crd-clusterrole
    repoURL: https://github.com/th2-net/th2-infra.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
