loki:
  # image:
  #   pullPolicy: IfNotPresent
  #   repository: grafana/loki
  #   pullSecrets:
  persistence:
    enabled: true
    existingClaim: loki
  config:
    compactor:
      retention_enabled: true
    limits_config:
      retention_period: 168h
promtail:
#   image:
#     pullPolicy: IfNotPresent
#     repository: grafana/promtail
#     pullSecrets:
  initContainer:
    - name: init
      image: docker.io/busybox:1.33
      imagePullPolicy: IfNotPresent
      command:
      - sh
      - -c
      - sysctl -w fs.inotify.max_user_instances=512
      securityContext:
        privileged: true
  resources:
    limits:
      cpu: 500m
      memory: 400Mi
    requests:
      cpu: 200m
      memory: 200Mi
  config:
    snippets:
      pipelineStages:
      - cri: {}
      - docker: {}
      - multiline:
          firstline: '^[\w :]+,\d+ \w+\s.*'
      - regex:
          expression: '^[\w :]+,\d+ (?P<level>[IEWDT]\w+)\s.*'
      - labels:
          level:

grafana:
  sidecar:
    datasources:
      enabled: false