loki:
  image:
    pullPolicy: IfNotPresent
    repository: grafana/loki
    tag: 2.0.0
    pullSecrets:
  persistence:
    enabled: true
    existingClaim: loki
  config:
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h
    chunk_store_config:
      max_look_back_period: 168h

promtail:
  image:
    pullPolicy: IfNotPresent
    repository: grafana/promtail
    tag: 2.0.0
    pullSecrets:
