global:
  imagePullSecrets:
alertmanager:
  alertmanagerSpec:
    image:
      repository: quay.io/prometheus/alertmanager
      tag: v0.20.0
prometheusOperator:
  image:
    repository: quay.io/coreos/prometheus-operator
    tag: v0.38.1
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
  prometheusConfigReloaderImage:
    repository: quay.io/coreos/prometheus-config-reloader
    tag: v0.38.1
  configmapReloadImage:
    repository: quay.io/coreos/configmap-reload
    tag: v0.0.1
  tlsProxy:
    enabled: false
prometheus:
  prometheusSpec:
    image:
      repository: quay.io/prometheus/prometheus
      tag: v2.18.1
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-storage
          selector:
            matchLabels:
              app: prometheus
          resources:
            requests:
              storage: 5Gi
grafana:
  image:
    repository: grafana/grafana
    tag: 7.0.3
    pullSecrets:
  sidecar:
    image:
      repository: kiwigrid/k8s-sidecar
      tag: 0.1.151
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/use-regex: "true"
    path: /grafana/?(.*)
    hosts: []
  grafana.ini:
    server:
      root_url: http://localhost:3000/grafana
  persistence:
    enabled: true
    existingClaim: grafana
  initChownData:
    enabled: false
    image:
      repository: busybox
      tag: 1.31.1
prometheus-node-exporter:
  imagePullSecrets:
  image:
    repository: quay.io/prometheus/node-exporter
    tag: v1.0.0
kube-state-metrics:
  image:
    repository: quay.io/coreos/kube-state-metrics
    tag: v1.9.6
