apiVersion: v1
kind: Service
metadata:
  name: cassandra-custom
spec:
  ports:
  - port: 32600
    nodePort: 32600
    protocol: TCP
    targetPort: 9042
  selector:
    app.kubernetes.io/name: cassandra
    app.kubernetes.io/version: 3.11.14
    cassandra.datastax.com/datacenter: th2
  type: NodePort