apiVersion: v1
kind: ConfigMap
metadata:
  name: medusa-config
data:
  medusa.ini: |-
    [cassandra]
    # The start and stop commands are not applicable in k8s.
    stop_cmd = /etc/init.d/cassandra stop
    start_cmd = /etc/init.d/cassandra start
    
    check_running = nodetool version
    use_sudo = False

    [storage]
    use_sudo_for_restore = False
    storage_provider = local
    base_path = /mnt/backups
    bucket_name = local
    max_backup_count = 7

    [grpc]
    enabled = 1

    [kubernetes]
    cassandra_url = http://127.0.0.1:8080/api/v0/ops/node/snapshots
    use_mgmt_api = 1
    enabled = 1

    [logging]
    level = DEBUG
  
  medusa.sh: |
    #!/bin/bash

    /bin/bash /home/cassandra/docker-entrypoint.sh &

    while true;
    do
        if [[ $(date +"%H-%M") == "02-30" ]]
        then
                medusa purge
                sleep 30
                medusa backup --backup-name $(date +"%m-%d-%y_%H-%M")_th2_cassandra_bkp
                sleep 30
        else
                echo $(date +"%H-%M")
                sleep 1m
        fi
    done