apiVersion: th2.exactpro.com/v2
kind: Th2Box
metadata:
  name: check1
spec:
  imageName: ghcr.io/th2-net/th2-check1
  imageVersion: 3.5.0
  type: th2-check1
  customConfig:
    message-cache-size: '1000'
    cleanup-older-than: '60'
    cleanup-time-unit: SECONDS
  extendedSettings:
    envVariables:
      JAVA_TOOL_OPTIONS: '-XX:+ExitOnOutOfMemoryError'
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
    service:
      enabled: true
      nodePort:
        - name: grpc
          exposedPort: 31989
  pins:
    mq:
      subscribers:
        - name: from_codec
          attributes:
            - subscribe
            - parsed
    grpc:
      server:
        - name: server
          serviceClasses:
            - PLEASE SPECIFY SERVICE CLASSES
