apiVersion: th2.exactpro.com/v2
kind: Th2Box
metadata:
  name: demo-conn1
spec:
  imageName: ghcr.io/th2-net/th2-conn-fix
  imageVersion: 2.1.0
  type: th2-conn
  customConfig:
    session-alias: demo-conn1
    workspace: /home/sailfish/workspace
    type: 'th2_service:FIX_Client'
    name: demo-conn1
    settings:
      autoStartable: true
      expectedTimeOfStarting: 2000
      invertStoredMessageTypes: false
      performDump: false
      persistMessages: true
      waitingTimeBeforeStarting: 0
      allowUnknownMsgFields: false
      beginString: FIXT.1.1
      checkLatency: false
      defaultApplVerID: 9
      duplicateTagsAllowed: false
      endTime: '00:00:00'
      fileStorePath: store/fix/sessions
      logHeartbeats: false
      maxLatency: 120
      microsecondsInTimeStampFields: false
      millisecondsInTimeStampFields: true
      orderingFields: false
      receiveLimit: 0
      rejectInvalidMessage: false
      resetOnDisconnect: false
      resetOnLogout: false
      senderCompID: DEMO-CONN1
      startTime: '00:00:00'
      targetCompID: FGW
      useLocalTime: false
      useSSL: false
      validateFieldsHaveValues: true
      validateFieldsOutOfOrder: true
      validateFieldsOutOfRange: true
      validateSequenceNumbers: true
      validateUserDefinedFields: true
      addNextExpectedMsgSeqNum: false
      autorelogin: true
      doLogonOnStart: true
      encryptPassword: false
      fakeResendRequest: true
      heartBtInt: 30
      idleTimeout: 0
      ignoreAbsenceOf141tag: false
      logonTimeout: 10
      logoutTimeout: 10
      performanceMode: false
      reconnectInterval: 5
      requiresOrigSendingTime: true
      resetSeqNumFlag: true
      seqNumSender: 0
      seqNumTarget: 0
      socketConnectHost: fix-demo-server1
      socketConnectPort: 8080
      useDefaultApplVerID: true
  extendedSettings:
    envVariables:
      JAVA_TOOL_OPTIONS: '-XX:+ExitOnOutOfMemoryError'
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
    service:
      enabled: false
  pins:
    mq:
      subscribers:
        - name: fix_to_send
          attributes:
            - send
            - parsed
            - subscribe
          filters:
            - metadata:
                - expectedValue: demo-conn1
                  fieldName: session_alias
                  operation: EQUAL
      publishers:
        - name: in
          attributes:
            - first
            - parsed
            - publish
            - store
        - name: in_raw
          attributes:
            - first
            - raw
            - publish
            - store
        - name: out
          attributes:
            - second
            - parsed
            - publish
            - store
        - name: out_raw
          attributes:
            - second
            - raw
            - publish
            - store
