apiVersion: th2.exactpro.com/v2
kind: Th2Box
metadata:
  name: fix-demo-server1
spec:
  imageName: ghcr.io/th2-net/th2-conn-fix
  imageVersion: 2.1.0
  type: th2-conn
  customConfig:
    session-alias: fix-demo-server1
    workspace: /home/sailfish/workspace
    type: 'th2_service:FIX_Server'
    name: fix-demo-server1
    settings:
      autoStartable: true
      expectedTimeOfStarting: 2000
      invertStoredMessageTypes: false
      performDump: false
      persistMessages: true
      waitingTimeBeforeStarting: 0
      allowUnknownMsgFields: false
      beginString: FIXT.1.1
      checkLatency: false
      defaultApplVerID: 9
      duplicateTagsAllowed: false
      endTime: '00:00:00'
      fileStorePath: store/fix/sessions
      logHeartbeats: true
      maxLatency: 120
      microsecondsInTimeStampFields: false
      millisecondsInTimeStampFields: true
      orderingFields: false
      receiveLimit: 0
      rejectInvalidMessage: false
      resetOnDisconnect: false
      resetOnLogout: false
      senderCompID: FGW
      startTime: '00:00:00'
      targetCompID: DEMO-CONN1
      useLocalTime: false
      useSSL: false
      validateFieldsHaveValues: true
      validateFieldsOutOfOrder: true
      validateFieldsOutOfRange: true
      validateSequenceNumbers: true
      validateUserDefinedFields: true
      applicationClassName: com.exactpro.sf.services.fix.ServerApplication
      keepMessagesInMemory: true
      socketAcceptPort: 8089
  extendedSettings:
    envVariables:
      JAVA_TOOL_OPTIONS: '-XX:+ExitOnOutOfMemoryError'
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
    service:
      enabled: false
  pins:
    mq:
      subscribers:
        - name: fix_to_send
          attributes:
            - send
            - parsed
            - subscribe
      publishers:
        - name: in
          attributes:
            - first
            - parsed
            - publish
            - store
        - name: in_raw
          attributes:
            - first
            - raw
            - publish
        - name: out
          attributes:
            - second
            - parsed
            - publish
        - name: out_raw
          attributes:
            - second
            - raw
            - publish
