apiVersion: th2.exactpro.com/v2
kind: Th2Box
metadata:
  name: util
spec:
  imageName: ghcr.io/th2-net/th2-util
  imageVersion: 3.1.0
  type: th2-util
  extendedSettings:
    envVariables:
      JAVA_TOOL_OPTIONS: '-XX:+ExitOnOutOfMemoryError'
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
    service:
      enabled: false
  pins:
    grpc:
      server:
        - name: server
          serviceClasses:
            - PLEASE SPECIFY SERVICE CLASSES
