{{/*
Generating configMap for k8
*/}}
{{- define "infraOperator-config" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-operator
data:
  infra-operator.yml: |
    ingressHost: {{ .Values.ingress.host | quote }}
    chartComponent:
      {{- toYaml .Values.infraOperator.config.chartComponent | nindent 6 }}
    chartDictionary:
      {{- toYaml .Values.infraOperator.config.chartDictionary | nindent 6 }}
    namespacePrefixes:
      {{- toYaml .Values.infraOperator.config.namespacePrefixes | nindent 6 }}
    k8sUrl: {{ .Values.infraOperator.config.k8sUrl | quote }}
    schemaSecrets:
      {{- if .Values.rabbitmq.fullnameOverride }}
      rabbitMQ: {{ .Values.rabbitmq.fullnameOverride }}
      {{- else }}
      rabbitMQ: {{ .Values.infraOperator.config.schemaSecrets.rabbitMQ | quote }}
      {{- end }}
      {{- if .Values.cassandra.fullnameOverride }}
      cassandra: {{ .Values.cassandra.fullnameOverride }}
      {{- else }}
      cassandra: {{ .Values.infraOperator.config.schemaSecrets.cassandra | quote }}
      {{- end }}
    rabbitMQManagement:
      {{- if .Values.rabbitmq.host }}
      host: {{ .Values.rabbitmq.host | quote }}
      {{- else }}
      host: "{{ .Values.rabbitmq.fullnameOverride }}-discovery.service.svc.cluster.local"
      {{- end }}
      port: {{ .Values.infraOperator.config.rabbitMQManagement.port | quote }}
      username: {{ .Values.infraOperator.config.rabbitMQManagement.username | quote }}
      password: {{ .Values.infraOperator.config.rabbitMQManagement.password | quote }}
      persistence: {{ .Values.infraOperator.config.rabbitMQManagement.persistence | quote }}
      schemaPermissions:
        configure: {{ .Values.infraOperator.config.rabbitMQManagement.schemaPermissions.configure | quote }}
        read: {{ .Values.infraOperator.config.rabbitMQManagement.schemaPermissions.read | quote }}
        write: {{ .Values.infraOperator.config.rabbitMQManagement.schemaPermissions.write | quote }}
{{ end }}
