{{/*
Generating configMap for k8
*/}}
{{- define "infraOperator-config" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-operator
  annotations:
  {{- include "common-annotations" . | nindent 4  }}
data:
  infra-operator.yml: |
    commonAnnotations:
    {{- include "common-annotations" . | nindent 6 }}
    ingress:
    {{- .Values.ingress | toYaml | nindent 6 }}
    prometheusConfiguration:
      host: "0.0.0.0"
      port: {{ .Values.infraOperator.prometheusConfiguration.port }}
      enabled: {{ .Values.infraOperator.prometheusConfiguration.enabled | quote }}
    chart:
      {{- toYaml .Values.infraOperator.config.chart | nindent 6 }}
    namespacePrefixes:
      {{- toYaml .Values.infraOperator.config.namespacePrefixes | nindent 6 }}
    k8sUrl: {{ .Values.infraOperator.config.k8sUrl | quote }}
    schemaSecrets:
      rabbitMQ: rabbitmq
      cassandra: cassandra
    rabbitMQManagement:
      {{- if .Values.rabbitmq.host }}
      host: {{ .Values.rabbitmq.host | quote }}
      {{- else }}
      host: "{{ .Values.rabbitmq.fullnameOverride }}-discovery.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
      {{- end }}
      port: {{ .Values.infraOperator.config.rabbitMQManagement.port | quote }}
      username: {{ .Values.infraOperator.config.rabbitMQManagement.username | quote }}
      password: {{ .Values.infraOperator.config.rabbitMQManagement.password | quote }}
      persistence: {{ .Values.infraOperator.config.rabbitMQManagement.persistence | quote }}
      schemaPermissions:
        configure: {{ .Values.infraOperator.config.rabbitMQManagement.schemaPermissions.configure | quote }}
        read: {{ .Values.infraOperator.config.rabbitMQManagement.schemaPermissions.read | quote }}
        write: {{ .Values.infraOperator.config.rabbitMQManagement.schemaPermissions.write | quote }}
{{ end }}
