{{- if .Values.rabbitmq.internal }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "rabbitmq-ha.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "rabbitmq-ha.name" . }}
    chart: {{ template "rabbitmq-ha.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  rabbitmq.conf: |
    ## disk space alarm
    disk_free_limit.{{ .Values.rabbitmq.diskFreeLimitType }} = {{ .Values.rabbitmq.diskFreeLimit }}
{{- end }}