# deprecated config, should be removed in the future
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: connectivity-config
  annotations:
    {{- if .Values.configMaps.annotations.default }}
    {{- toYaml $.Values.configMaps.annotations.default | nindent 4 }}
    {{- end }}
    {{- if .Values.configMaps.annotations.extra }}
    {{- toYaml $.Values.configMaps.annotations.extra | nindent 4 }}
    {{- end }}
data:
  TH2_CONNECTIVITY_ADDRESSES: ''
