# deprecated config, should be removed in the future
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: connectivity-config
  annotations:
  {{- include "common-annotaitions" . | nindent 4  }}
data:
  TH2_CONNECTIVITY_ADDRESSES: ''
