apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbit-mq-external-app-config
data:
  rabbitMQ.json: |
    {
    {{- if .Values.rabbitmq.host }}
    "host": {{ .Values.rabbitmq.host | quote }},
    "port": "5672",
    {{- else }}
    "host": {{ .Values.ingress.host | quote }},
    "port": {{ .Values.rabbitmq.service.amqpNodePort | quote }},
    {{- end }}
    "vHost": "",
    "username": "",
    "password": "${RABBITMQ_PASS}",
    "exchangeName": {{ .Values.rabbitmq.rabbitmqExchange | quote }}
    }
