apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbit-mq-external-app-config
  annotations:
    {{- if .Values.configMaps.annotations.default }}
    {{- toYaml $.Values.configMaps.annotations.default | nindent 4 }}
    {{- end }}
    {{- if .Values.configMaps.annotations.extra }}
    {{- toYaml $.Values.configMaps.annotations.extra | nindent 4 }}
    {{- end }}
data:
  rabbitMQ.json: |
    {
    {{- if .Values.rabbitmq.host }}
    "host": {{ .Values.rabbitmq.host | quote }},
    "port": "5672",
    {{- else }}
    "host": {{ .Values.externalRabbitMQHost.host | quote }},
    "port": {{ .Values.rabbitmq.service.amqpNodePort | quote }},
    {{- end }}
    "vHost": "",
    "username": "",
    "password": "${RABBITMQ_PASS}",
    "exchangeName": {{ .Values.rabbitmq.rabbitmqExchange | quote }}
    }
