apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbit-mq-app-config
  annotations:
    {{- if .Values.configMaps.annotations.default }}
    {{- toYaml $.Values.configMaps.annotations.default | nindent 4 }}
    {{- end }}
    {{- if .Values.configMaps.annotations.extra }}
    {{- toYaml $.Values.configMaps.annotations.extra | nindent 4 }}
    {{- end }}
data:
  rabbitMQ.json: |
    {
    {{- if .Values.rabbitmq.host }}
    "host": {{ .Values.rabbitmq.host | quote }},
    {{- else }}
    "host": "{{ .Values.rabbitmq.fullnameOverride }}-discovery.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}",
    {{- end }}
    "vHost": "",
    "port": "5672",
    "username": "",
    "password": "${RABBITMQ_PASS}",
    "exchangeName": {{ .Values.rabbitmq.rabbitmqExchange | quote }}
    }
