apiVersion: v1
kind: Secret
metadata:
  name: th2-git-access-schemas
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "th2.labels" . | nindent 4 }}
type: Opaque
data:
  httpAuthUsername: {{ .Values.infraMgr.git.httpAuthUsername | b64enc | quote }} 
  httpAuthPassword: {{ .Values.infraMgr.git.httpAuthPassword | b64enc | quote }}
