{{- if not .Values.rabbitmq.internal -}}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  annotations:
  {{- include "common-annotaitions" . | nindent 4  }}
  labels:
    {{- include "th2.labels" . | nindent 4 }}
type: Opaque
data:
  rabbitmq-password: {{ .Values.rabbitmq.rabbitmqPassword | b64enc | quote }}
  rabbitmq-management-password: {{ .Values.rabbitmq.managementPassword | b64enc | quote }}
{{- end -}}
