apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: th2coreboxes.th2.exactpro.com
spec:
  additionalPrinterColumns:
    - JSONPath: .status.subResourceName
      name: HelmRelease
      type: string
    - JSONPath: .spec.type
      name: Type
      type: string
    - JSONPath: .status.phase
      name: Status
      type: string
    - JSONPath: .status.message
      name: Message
      type: string
    - JSONPath: .metadata.creationTimestamp
      name: Age
      type: date
  group: th2.exactpro.com
  names:
    kind: Th2CoreBox
    listKind: Th2CoreBoxList
    plural: th2coreboxes
    singular: th2corebox
  scope: Namespaced
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      required:
        - spec
      description: Th2CoreBox defines Th2 core component instance
      properties:
        apiVersion:
          description: ""
          type: string
        kind:
          description: ""
          type: string
        metadata:
          type: object
        spec:
          type: object
          description: Specification of desired box
          properties:
            image-name:
              type: string
            image-version:
              type: string
            type:
              type: string
              enum:
                [
                  th2-act,
                  th2-codec,
                  th2-conn,
                  th2-rpt-data-provider,
                  th2-rpt-viewer,
                  th2-check1,
                  th2-check2-bookcheck,
                  th2-check2-recon,
                  th2-script,
                  th2-sim,
                  th2-hand,
                  th2-read,
                  th2-util,
                  th2-cradle-viewer,
                ]
            extended-settings:
              type: object
              description: ""
              properties:
                chart-cfg:
                  type: object
                  description: ""
                  properties:
                    ref:
                      type: string
                    path:
                      type: string
                service:
                  type: object
                  description: ""
                  properties:
                    enabled:
                      type: string
                      enum: ["false", "true"]
                    type:
                      type: string
                      enum: [ClusterIP, NodePort, LoadBalancer, ExternalName]
                    targetPort:
                      type: string
                    nodePort:
                      type: string
                    endpoints:
                      type: array
                      description: ""
                      items:
                        type: object
                        description: ""
                        properties:
                          name:
                            type: string
                          targetPort:
                            type: string
                          nodePort:
                            type: string
                        required:
                          - name
                          - targetPort
                envVariables:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                externalBox:
                  type: object
                  description: ""
                  properties:
                    enabled:
                      type: string
                      enum: ["false", "true"]
                    address:
                      type: string
                    endpoints:
                      type: array
                      description: ""
                      items:
                        type: object
                        description: ""
                        properties:
                          name:
                            type: string
                          targetPort:
                            type: string
                        required:
                          - name
                          - targetPort
                hostNetwork:
                  type: string
                  enum: ["false", "true"]
                resources:
                  type: object
                  description: ""
                  properties:
                    limits:
                      type: object
                      description: ""
                      properties:
                        memory:
                          type: string
                        cpu:
                          type: string
                    requests:
                      type: object
                      description: ""
                      properties:
                        memory:
                          type: string
                        cpu:
                          type: string
                mounting:
                  type: array
                  description: ""
                  items:
                    type: object
                    description: ""
                    properties:
                      pvcName:
                        type: string
                      path:
                        type: string
            prometheus:
              type: object
              properties:
                host:
                  type: string
                port:
                  type: string
                enabled:
                  type: string
                  enum: ["false", "true"]
            custom-config:
              type: object
              description: this is custom configuration
              x-kubernetes-preserve-unknown-fields: true
            params:
              type: array
              description: List of generic parameters
              items:
                type: object
                description: ""
                properties:
                  name:
                    type: string
                  value:
                    type: string
                required:
                  - name
                  - value
            pins:
              type: array
              description: List of connection pins
              items:
                type: object
                description: ""
                properties:
                  name:
                    type: string
                  connection-type:
                    type: string
                    enum: [mq, grpc]
                  settings:
                    type: object
                    description: ""
                    properties:
                      storageOnDemand:
                        type: string
                        enum: ["false", "true"]
                      queueLength:
                        type: string
                  attributes:
                    type: array
                    items:
                      type: string
                  filters:
                    type: array
                    description: ""
                    items:
                      type: object
                      description: ""
                      properties:
                        metadata:
                          type: array
                          description: ""
                          items:
                            type: object
                            description: ""
                            properties:
                              field-name:
                                type: string
                              expected-value:
                                type: string
                              operation:
                                type: string
                                enum: [EQUAL, NOT_EQUAL, EMPTY, NOT_EMPTY]
                            required:
                              - field-name
                              - expected-value
                              - operation
                        message:
                          type: array
                          description: ""
                          items:
                            type: object
                            description: ""
                            properties:
                              field-name:
                                type: string
                              expected-value:
                                type: string
                              operation:
                                type: string
                                enum: [EQUAL, NOT_EQUAL, EMPTY, NOT_EMPTY]
                            required:
                              - field-name
                              - expected-value
                              - operation
                required:
                  - name
                  - connection-type
          required:
            - image-name
            - image-version
            - type
        status:
          description: contains status information about this resource
          type: object
          properties:
            conditions:
              description: Conditions contains observations of the resource's state
              type: array
              items:
                type: object
                required:
                  - status
                  - type
                properties:
                  lastTransitionTime:
                    description:
                      LastTransitionTime is the timestamp corresponding
                      to the last status change of this condition.
                    type: string
                    format: date-time
                  lastUpdateTime:
                    description:
                      LastUpdateTime is the timestamp corresponding to
                      the last status update of this condition.
                    type: string
                    format: date-time
                  message:
                    nullable: true
                    description:
                      Message is a human readable description of the details
                      of the last transition, complementing reason.
                    type: string
                  reason:
                    description:
                      Reason is a brief machine readable explanation for
                      the condition's last transition.
                    type: string
                  status:
                    description: Status of the condition, one of ('True', 'False', 'Unknown').
                    type: string
                    enum:
                      - "True"
                      - "False"
                      - Unknown
                  type:
                    description: Type of the condition
                    type: string
                    enum:
                      - Deployed
                      - Enqueued
            subResourceName:
              description: SubResourceName is the name of produced helmrelease tied with this resource
              type: string
            phase:
              description: ComponentStatus is the status as given by Operator for this resource
              type: string
            message:
              description: Message describe current state of this resource
              type: string
  version: v1
  versions:
    - name: v1
      served: true
      storage: true

    # subresources describes the subresources for custom resources.
  subresources:
    # status enables the status subresource.
    status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
