apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: th2estores.th2.exactpro.com
spec:
  conversion:
    strategy: None
  group: th2.exactpro.com
  names:
    kind: Th2Estore
    listKind: Th2EstoreList
    plural: th2estores
    singular: th2estore
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.subResourceName
      name: HelmRelease
      type: string
    - jsonPath: .status.phase
      name: Status
      type: string
    - jsonPath: .status.message
      name: Message
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: Th2Estore defines th2 event store instance
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            description: Specification of desired event store
            properties:
              custom-config:
                description: this is custom configuration
                type: object
                x-kubernetes-preserve-unknown-fields: true
              extended-settings:
                properties:
                  chart-cfg:
                    properties:
                      path:
                        type: string
                      ref:
                        type: string
                    type: object
                  envVariables:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  externalBox:
                    properties:
                      address:
                        type: string
                      enabled:
                        enum:
                        - "false"
                        - "true"
                        type: string
                      endpoints:
                        items:
                          properties:
                            name:
                              type: string
                            targetPort:
                              type: string
                          required:
                          - name
                          - targetPort
                          type: object
                        type: array
                    type: object
                  hostNetwork:
                    enum:
                    - "false"
                    - "true"
                    type: string
                  mounting:
                    items:
                      properties:
                        path:
                          type: string
                        pvcName:
                          type: string
                      type: object
                    type: array
                  resources:
                    properties:
                      limits:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                        type: object
                      requests:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                        type: object
                    type: object
                  service:
                    properties:
                      enabled:
                        enum:
                        - "false"
                        - "true"
                        type: string
                      endpoints:
                        items:
                          properties:
                            name:
                              type: string
                            nodePort:
                              type: string
                            targetPort:
                              type: string
                          required:
                          - name
                          - targetPort
                          type: object
                        type: array
                      nodePort:
                        type: string
                      targetPort:
                        type: string
                      type:
                        enum:
                        - ClusterIP
                        - NodePort
                        - LoadBalancer
                        - ExternalName
                        type: string
                    type: object
                type: object
              image-name:
                type: string
              image-version:
                type: string
              params:
                description: List of generic parameters
                items:
                  properties:
                    name:
                      type: string
                    value:
                      type: string
                  required:
                  - name
                  - value
                  type: object
                type: array
              prometheus:
                properties:
                  enabled:
                    enum:
                    - "false"
                    - "true"
                    type: string
                  host:
                    type: string
                  port:
                    type: string
                type: object
              type:
                enum:
                - th2-estore
                type: string
            required:
            - image-name
            - image-version
            type: object
          status:
            description: contains status information about this resource
            properties:
              conditions:
                description: Conditions contains observations of the resource's state
                items:
                  properties:
                    lastTransitionTime:
                      description: LastTransitionTime is the timestamp corresponding
                        to the last status change of this condition.
                      format: date-time
                      type: string
                    lastUpdateTime:
                      description: LastUpdateTime is the timestamp corresponding to
                        the last status update of this condition.
                      format: date-time
                      type: string
                    message:
                      description: Message is a human readable description of the
                        details of the last transition, complementing reason.
                      nullable: true
                      type: string
                    reason:
                      description: Reason is a brief machine readable explanation
                        for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of ('True', 'False',
                        'Unknown').
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: Type of the condition
                      enum:
                      - Deployed
                      - Enqueued
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              message:
                description: Message describe current state of this resource
                type: string
              phase:
                description: ComponentStatus is the status as given by Operator for
                  this resource
                type: string
              subResourceName:
                description: SubResourceName is the name of produced helmrelease tied
                  with this resource
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    listKind: ""
    plural: ""
    singular: ""
  conditions: []
  storedVersions: []
