{{/* 
Generating container port for prometheus stats from pods
*/}}
{{- define "prometheus-deploy" }}
        {{- if not .component.prometheus }}
        ports:
        - name: metrics
          containerPort: 9752
        {{- else }}
        {{- if .component.prometheus.enabled }}
        ports:
        - name: metrics
          {{- if .component.prometheus.port }}
          containerPort: {{ .component.prometheus.port }}
          {{- else }}
          containerPort: 9752
          {{- end }}
        {{- end }}
        {{- end }}
{{- end }}
