{{/*
Generating service for pod
*/}}
{{- define "service" }}
---
{{- if not .Values.component.extendedSettings.service }}
{{- include "prometheus-service" .Values }}
{{- else }}

{{- if .Values.component.extendedSettings.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component.name }}
  annotations:
  {{- include "common-annotations" .Values | nindent 4  }}
  {{- if .Values.component.prometheus }}{{- if .Values.component.prometheus.enabled }}
  labels:
    monitoring-pod: "true"
  {{- end }}{{- end }}
spec:
  selector:
    app: {{ .Values.component.name }}
    {{- if .Values.component.extendedSettings.service.nodePort }}
  type: nodePort
  ports:
    {{- include "svc-ports" . }}
    {{- end }}

    {{- if .Values.component.extendedSettings.service.clusterIP }}
  type: ClusterIP
  ports:
    {{- include "svc-ports" . }}
    {{- end }}
    {{- include "svc-prometheus-port" .Values }}

{{- else }}
{{- include "prometheus-service" .Values }}
{{- end }}
{{- end }}
{{- end }}
