{{- if .Values.component.extendedSettings.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component.name }}
  {{- if .Values.annotations }}
{{- include "annotations" .Values }}
  {{- end }}
  {{- if .Values.component.prometheus }}{{- if .Values.component.prometheus.enabled }}
  labels:
    monitoring-pod: "true"
  {{- end }}{{- end }}
spec:
  selector:
    app: {{ .Values.component.name }}
  {{- if not .Values.component.extendedSettings.service.type }}
  ports:
    - protocol: TCP
      name: app-default
      port: 8080
      targetPort: 8080
  {{- else }}
  type: {{ .Values.component.extendedSettings.service.type }}
  ports:
    {{- include "svc-ports" . }}
  {{- end }}
    {{- include "svc-prometheus-port" .Values }}

{{- else }}

{{- if .Values.component.prometheus }}{{- if .Values.component.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component.name }}
  {{- if .Values.annotations }}
{{- include "annotations" .Values }}
  {{- end }}
  labels:
    monitoring-pod: "true"
spec:
  selector:
    app: {{ .Values.component.name }}
  ports:
    {{- include "svc-prometheus-port" .Values }}
{{- end }}{{- end }}

{{- end }}
