# To create CRDs the following permission should be granted to `openshift-gitops-argocd-application-controller` ServiceAccount:
# ```console
# oc create clusterrole createcrds --verb=* --resource=apiextensions.k8s.io.customresourcedefinitions
# oc adm policy add-cluster-role-to-user createcrds system:serviceaccount:openshift-gitops:openshift-gitops-argocd-application-controller
# ```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: th2-gitops
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - bitnami.com
  resources:
  - sealedsecrets
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: th2-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: th2-gitops
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops