apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: th2estores.th2.exactpro.com
spec:
  conversion:
    strategy: None
  group: th2.exactpro.com
  names:
    kind: Th2Estore
    listKind: Th2EstoreList
    plural: th2estores
    singular: th2estore
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.subResourceName
      name: HelmRelease
      type: string
    - jsonPath: .status.phase
      name: Status
      type: string
    - jsonPath: .status.message
      name: Message
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v2
    schema:
      openAPIV3Schema:
        description: Th2Estore defines th2 event store instance
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            description: Specification of desired event store
            properties:
              customConfig:
                description: this is custom configuration
                type: object
                x-kubernetes-preserve-unknown-fields: true
              loggingConfig:
                type: string
              mqRouter:
                description: this is custom configuration for router mq
                type: object
                x-kubernetes-preserve-unknown-fields: true
              grpcRouter:
                description: this is custom configuration for router grpc
                type: object
                x-kubernetes-preserve-unknown-fields: true
              cradleManager:
                description: this is custom configuration for cradle
                type: object
                x-kubernetes-preserve-unknown-fields: true
              bookName:
                type: string
              extendedSettings:
                properties:
                  chartCfg:
                    properties:
                      path:
                        type: string
                      ref:
                        type: string
                    type: object
                  replicas:
                    type: integer
                  k8sProbes:
                    type: boolean
                    default: false
                  envVariables:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  sharedMemory:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                  externalBox:
                    properties:
                      address:
                        type: string
                      enabled:
                        type: boolean
                      endpoints:
                        items:
                          properties:
                            name:
                              type: string
                            targetPort:
                              type: integer
                          required:
                          - name
                          - targetPort
                          type: object
                        type: array
                    type: object
                  hostAliases:
                    description: HostAliases is an optional list of hosts and IPs that will be injected into the pod's hosts file if specified. This is only valid for non-hostNetwork pods.
                    type: array
                    items:
                      properties:
                        ip:
                          description: IP address of the host file entry.
                          type: string
                        hostnames:
                          description: Hostnames for the above IP address.
                          items:
                            type: string
                          type: array
                      required:
                        - ip
                        - hostnames
                      type: object
                  hostNetwork:
                    type: boolean
                  nodeSelector:
                    additionalProperties:
                      type: string
                    description: |
                      NodeSelector is a selector which must be true for the pod to fit on a node.
                      Selector which must match a node's labels for the pod to be scheduled on that node. More info: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
                    type: object
                  bookName:
                    type: string
                  mounting:
                    items:
                      properties:
                        path:
                          type: string
                        pvcName:
                          type: string
                      type: object
                    type: array
                  resources:
                    properties:
                      limits:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                        type: object
                      requests:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                        type: object
                    type: object
                  service:
                    properties:
                      enabled:
                        type: boolean
                      endpoints:
                        items:
                          properties:
                            name:
                              type: string
                            nodePort:
                              type: integer
                            targetPort:
                              type: integer
                            port:
                              type: integer
                          required:
                          - name
                          type: object
                        type: array
                      type:
                        enum:
                        - ClusterIP
                        - NodePort
                        - LoadBalancer
                        - ExternalName
                        type: string
                      ingress:
                        type: object
                        properties:
                          urlPaths:
                            type: array
                            items:
                              type: string
                              pattern: "^[-a-zA-Z0-9_/]+$"
              disabled:
                type: boolean
              imageName:
                type: string
              imageVersion:
                type: string
              versionRange:
                type: string
              params:
                description: List of generic parameters
                items:
                  properties:
                    name:
                      type: string
                    value:
                      type: string
                  required:
                  - name
                  - value
                  type: object
                type: array
              prometheus:
                properties:
                  enabled:
                    type: boolean
                  host:
                    type: string
                  port:
                    type: integer
                type: object
              type:
                enum:
                - th2-estore
                type: string
            required:
            - imageName
            - imageVersion
            type: object
          status:
            description: contains status information about this resource
            properties:
              conditions:
                description: Conditions contains observations of the resource's state
                items:
                  properties:
                    lastTransitionTime:
                      description: LastTransitionTime is the timestamp corresponding
                        to the last status change of this condition.
                      format: date-time
                      type: string
                    lastUpdateTime:
                      description: LastUpdateTime is the timestamp corresponding to
                        the last status update of this condition.
                      format: date-time
                      type: string
                    message:
                      description: Message is a human readable description of the
                        details of the last transition, complementing reason.
                      nullable: true
                      type: string
                    reason:
                      description: Reason is a brief machine readable explanation
                        for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of ('True', 'False',
                        'Unknown').
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: Type of the condition
                      enum:
                      - Deployed
                      - Enqueued
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              message:
                description: Message describe current state of this resource
                type: string
              phase:
                description: ComponentStatus is the status as given by Operator for
                  this resource
                type: string
              subResourceName:
                description: SubResourceName is the name of produced helmrelease tied
                  with this resource
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    listKind: ""
    plural: ""
    singular: ""
  conditions: []
  storedVersions: []
