apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: th2mstores.th2.exactpro.com
spec:
  conversion:
    strategy: None
  group: th2.exactpro.com
  names:
    kind: Th2Mstore
    listKind: Th2MstoreList
    plural: th2mstores
    singular: th2mstore
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.subResourceName
      name: HelmRelease
      type: string
    - jsonPath: .status.phase
      name: Status
      type: string
    - jsonPath: .status.message
      name: Message
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v2
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            description: Specification of desired message store
            properties:
              customConfig:
                description: this is custom configuration
                type: object
                x-kubernetes-preserve-unknown-fields: true
              loggingConfig:
                description: this is logging configuration
                type: string
              mqRouter:
                description: this is custom configuration for router mq
                type: object
                x-kubernetes-preserve-unknown-fields: true
              grpcRouter:
                description: this is custom configuration for router grpc
                type: object
                x-kubernetes-preserve-unknown-fields: true
              cradleManager:
                description: this is custom configuration for cradle
                type: object
                x-kubernetes-preserve-unknown-fields: true
              bookName:
                description: Can be used for passing custom book for a specific CR
                type: string
              extendedSettings:
                type: object
                description: section for extended settings
                properties:
                  chartCfg:
                    description: specifies which charts to use for rolling out infra
                    properties:
                      path:
                        description: DESCRIPTION NEEDED
                        type: string
                      ref:
                        description: DESCRIPTION NEEDED
                        type: string
                    type: object
                  replicas:
                    description: number of replicas
                    type: integer
                  k8sProbes:
                    description: if enabled liveness probes will be collected from pod
                    type: boolean
                    default: false
                  envVariables:
                    description: allows us to pass specific environment variables that are going to be set into the pods.
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  sharedMemory:
                    description: DESCRIPTION NEEDED
                    type: object
                    properties:
                      enabled:
                        description: DESCRIPTION NEEDED
                        type: boolean
                  externalBox:
                    description: using this section we can configure boxes that are going to be run outside of kubernetes cluster
                    properties:
                      address:
                        description: address to the machine on which external box is running
                        type: string
                      enabled:
                        description: represents the state of the external box
                        type: boolean
                      endpoints:
                        description: internal mapping for ports
                        items:
                          properties:
                            name:
                              description: name for the endpoint
                              type: string
                            targetPort:
                              description: value for exposed port
                              type: integer
                          required:
                          - name
                          - targetPort
                          type: object
                        type: array
                    type: object
                  hostAliases:
                    description: HostAliases is an optional list of hosts and IPs that will be injected into the pod's hosts file if specified. This is only valid for non-hostNetwork pods.
                    type: array
                    items:
                      properties:
                        ip:
                          description: IP address of the host file entry.
                          type: string
                        hostnames:
                          description: Hostnames for the above IP address.
                          items:
                            type: string
                          type: array
                      required:
                        - ip
                        - hostnames
                      type: object
                  hostNetwork:
                    description: if the flag is set to true, pod will run on node network and kubernetes will decide which node will be used for running the box.
                    type: boolean
                  nodeSelector:
                    additionalProperties:
                      type: string
                    description: |
                      NodeSelector is a selector which must be true for the pod to fit on a node.
                      Selector which must match a node's labels for the pod to be scheduled on that node. More info: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
                    type: object
                  mounting:
                    description: allows to configure persistent volume mounting for pods
                    items:
                      properties:
                        path:
                          description: a directory in pod where you mount external folder
                          type: string
                        pvcName:
                          description: name for the pvc
                          type: string
                      type: object
                    type: array
                  resources:
                    description: here we can specify resource limitations and allowances for this specific component
                    properties:
                      limits:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                        type: object
                      requests:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                        type: object
                    type: object
                  service:
                    type: object
                    properties:
                      enabled:
                        description: if enabled allows pod to be exposed using ClusterIP
                        type: boolean
                      clusterIP:
                        description: endpoints for cluster IP service type
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              description: name of the endpoint
                              type: string
                            containerPort:
                              description: allows to specify Kubernetes port for the pod.
                              type: integer
                        required:
                          - name
                      nodePort:
                        description: endpoints for cluster IP service type
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              description: name of the endpoint
                              type: string
                            exposedPort:
                              description: a port on which the service will be accessible.
                              type: integer
                            containerPort:
                              description: allows to specify Kubernetes port for the pod.
                              type: integer
                        required:
                          - name
                          - exposedPort
                      ingress:
                        description: section for ingress
                        type: object
                        properties:
                          urlPaths:
                            description: url paths
                            type: array
                            items:
                              type: string
                              pattern: "^[-a-zA-Z0-9_/]+$"
                    type: object
                type: object
              disabled:
                description: if set to true resource will act as if it is removed from schema without actually deleting the file. The default value is false.
                type: boolean
              imageName:
                description: docker image repository URL
                type: string
              imageVersion:
                description: docker image tag
                type: string
              versionRange:
                description: when the appropriate pattern is provided, image-version will be updated with the latest tag from the image repository that satisfies that pattern.
                type: string
              params:
                description: List of generic parameters
                items:
                  properties:
                    name:
                      description: name of parameter
                      type: string
                    value:
                      description: value of parameter
                      type: string
                  required:
                  - name
                  - value
                  type: object
                type: array
              prometheus:
                description: custom configuration of prometheus for microservices
                properties:
                  enabled:
                    description: By default this is set to true.
                    type: boolean
                  host:
                    description: host for prometheus
                    type: string
                  port:
                    description: port for prometheus
                    type: integer
                type: object
              type:
                enum:
                - th2-mstore
                type: string
            required:
            - imageName
            - imageVersion
            type: object
          status:
            description: contains status information about this resource
            properties:
              conditions:
                description: Conditions contains observations of the resource's state
                items:
                  properties:
                    lastTransitionTime:
                      description: LastTransitionTime is the timestamp corresponding
                        to the last status change of this condition.
                      format: date-time
                      type: string
                    lastUpdateTime:
                      description: LastUpdateTime is the timestamp corresponding to
                        the last status update of this condition.
                      format: date-time
                      type: string
                    message:
                      description: Message is a human readable description of the
                        details of the last transition, complementing reason.
                      nullable: true
                      type: string
                    reason:
                      description: Reason is a brief machine readable explanation
                        for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of ('True', 'False',
                        'Unknown').
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: Type of the condition
                      enum:
                      - Deployed
                      - Enqueued
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              message:
                description: Message describe current state of this resource
                type: string
              phase:
                description: ComponentStatus is the status as given by Operator for
                  this resource
                type: string
              subResourceName:
                description: SubResourceName is the name of produced helmrelease tied
                  with this resource
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    listKind: ""
    plural: ""
    singular: ""
  conditions: []
  storedVersions: []
