apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: th2dictionaries.th2.exactpro.com
spec:
  conversion:
    strategy: None
  group: th2.exactpro.com
  names:
    kind: Th2Dictionary
    listKind: Th2DictionaryList
    plural: th2dictionaries
    singular: th2dictionary
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            description: Specification of desired dictionary
            properties:
              compressed:
                description: Indicates whether dictionary's data is already compressed. If set to true, no further compression will take place in infra. default is set to false
                type: boolean
              data:
                description: data for the dictionary
                type: string
            required:
            - data
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    listKind: ""
    plural: ""
    singular: ""
  conditions: []
  storedVersions: []
