registries:
  nexus.data.com:30000:
    username: user
    password: pwd
infraGit:
  internal: true
externalRabbitMQHost:
  host: localhost
rabbitmq:
  auth:
    username: th2
    password: test
  persistence:
    enabled: false
  prometheus:
    operator:
      enabled: false
  metrics:
    enabled: false
cassandra:
  # existingConfiguration: cassandra-configuration
  # initDBConfigMap: cassandra-init
  dbUser:
    user: cassandra
    password: cassandra
  cluster:
    datacenter: datacenter1
  jvm:
    maxHeapSize: 1G
    newHeapSize: 800M
  internal: true
infraMgr:
  git:
    repository: ssh://git@infra-git:22/home/git/repo/e2e-test-schema.git
infraOperator:
  config:
    chart:
      git: https://github.com/th2-net/infra-operator-tpl.git
      ref: release-v0.7.2
      path: ./
