infraGit:
  internal: true
externalRabbitMQHost:
  host: localhost
rabbitmq:
  auth:
    username: th2
    password: test
  persistence:
    enabled: false
  prometheus:
    operator:
      enabled: true
  metrics:
    enabled: false
cassandra:
  # existingConfiguration: cassandra-configuration
  initDBConfigMap: cassandra-init
  dbUser:
    user: cassandra
    password: cassandra
  cluster:
    numTokens: 16
    datacenter: datacenter1
  jvm:
    maxHeapSize: 1G
    newHeapSize: 800M
    extraOpts: "-Dcassandra.skip_wait_for_gossip_to_settle=0"
  internal: true
infraMgr:
  git:
    repository: ssh://git@infra-git:22/home/git/repo/e2e-test-schema.git
