commonAnnotations:
  e2ecommon: "test-common-annotation"
infraGit:
  internal: true
infraRepo:
  image:
    tag: e2e
externalRabbitMQHost:
  host: localhost
jupyterhub:
  internal: true
  proxy:
    secretToken: 65589277c5c121351c9a15199b67f8a52c651dd636e5c3f727f7a00df88a7c9c
    service:
      type: NodePort
  hub:
    service:
      type: NodePort
    db:
      type: sqlite-pvc
      pvc:
        selector:
          matchLabels:
            app: jupyter-db
        annotations: {}
        accessModes:
          - ReadWriteOnce
        storage: 200Mi
        storageClassName: local-storage
  singleuser:
    storage:
      capacity: 200Mi
      static:
        pvcName: jupiter-users-volume
        subPath: '{username}'
      type: static
rabbitmq:
  auth:
    username: th2
    password: test
  persistence:
    enabled: false
  prometheus:
    operator:
      enabled: true
  metrics:
    enabled: false
cassandra:
  # existingConfiguration: cassandra-configuration
  initDBConfigMap: cassandra-init
  dbUser:
    user: cassandra
    password: cassandra
  cluster:
    numTokens: 16
    datacenter: datacenter1
  jvm:
    maxHeapSize: 1G
    newHeapSize: 800M
    extraOpts: "-Dcassandra.skip_wait_for_gossip_to_settle=0"
  internal: true
infraMgr:
  git:
    repository: ssh://git@infra-git:22/home/git/repo/e2e-test-schema.git
