commonAnnotations:
  e2ecommon: "test-common-annotation"
infraGit:
  internal: true
infraRepo:
  image:
    tag: e2e
externalRabbitMQHost:
  host: localhost
rabbitmq:
  auth:
    username: th2
    password: test
  persistence:
    enabled: false
  prometheus:
    operator:
      enabled: true
  metrics:
    enabled: false
jupyterhub:
  custom:
    internal: true
cassandra:
  # existingConfiguration: cassandra-configuration
  initDBConfigMap: cassandra-init
  dbUser:
    user: cassandra
    password: cassandra
  cluster:
    numTokens: 16
    datacenter: datacenter1
  jvm:
    maxHeapSize: 1G
    newHeapSize: 800M
    extraOpts: "-Dcassandra.skip_wait_for_gossip_to_settle=0"
  internal: true
infraMgr:
  git:
    repository: ssh://git@infra-git:22/home/git/repo/e2e-test-schema.git
converter:
  git:
    repository: ssh://git@infra-git:22/home/git/repo/e2e-test-schema.git
