infraGit:
  internal: true
externalRabbitMQHost:
  host: localhost
rabbitmq:
  rabbitmqUser: th2
  rabbitmqPassword: test
  persistentVolume:
    enabled: false
  prometheus:
    operator:
      enabled: false
cassandra:
  # existingConfiguration: cassandra-configuration
  # initDBConfigMap: cassandra-init
  dbUser:
    user: cassandra
    password: cassandra
  cluster:
    datacenter: datacenter1
  jvm:
    maxHeapSize: 1G
    newHeapSize: 800M
  internal: true
infraMgr:
  git:
    repository: ssh://git@infra-git:22/home/git/repo/e2e-test-schema.git
