---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-jupiter-users
  labels:
    app: jupiter-users
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /opt/jupiter_users
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - chart-testing-control-plane
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-jupyter-db
  labels:
    app: jupyter-db
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /opt/jupiter_db
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - chart-testing-control-plane
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jupiter-users-volume
  namespace: service
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      app: jupiter-users