apiVersion: v1
kind: ConfigMap
metadata:
  name: keys-repo
<<<<<<< HEAD
  namespace: service
=======
  namespace: "{{ infra_namespace }}"
>>>>>>> origin/release-v1.8.0
data:
  authorized_keys: "{{ lookup('file', 'id_ssh_rsa.pub') }}"
