---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
spec:
  destination:
    namespace: argo-monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.6.5
    helm:
      valueFiles:
      - $values/argocd/openshift/monitoring/loki-values.yaml
  - repoURL: https://github.com/th2-net/th2-infra.git
    targetRevision: release-v2.1.0-argocd
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-access
spec:
  destination:
    namespace: argo-monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: false
    path: argocd/openshift/monitoring/grafana-access
    repoURL: https://github.com/th2-net/th2-infra.git
    targetRevision: release-v2.1.0-argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true