{{/*
Generating configMap for k8
*/}}
{{- define "infraMgr-config" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-mgr
data:
  config.yml: |
    prometheusConfiguration:
      host: "0.0.0.0"
      port: {{ default 9752 .Values.infraMgr.prometheusConfiguration.port }}
      enabled: {{ default true .Values.infraMgr.prometheusConfiguration.enabled }}
    git:
      remoteRepository: {{ .Values.infraMgr.git.repository }}
      localRepositoryRoot: {{ .Values.infraMgr.git.repositoryLocalCache }}
      privateKeyFile: {{ .Values.infraMgr.git.secretMountPath }}/{{ .Values.infraMgr.git.privateKeyFileSecret }}
      ignoreInsecureHosts: true
      httpAuthUsername: "${HTTPS_AUTH_USERNAME}"
      httpAuthPassword: "${HTTPS_AUTH_PASSWORD}"

    rabbitmq:
      vhostName: {{ .Values.rabbitmq.rabbitmqVhost | quote }}
      secret: {{ default .Values.infraMgr.rabbitmq.secret .Values.rabbitmq.fullnameOverride }}
      passwordLength: {{ .Values.infraMgr.rabbitmq.passwordLength }}

    cassandra:
      keyspacePrefix: {{ .Values.infraMgr.cassandra.keyspacePrefix }}
      secret: {{ default .Values.infraMgr.cassandra.secret .Values.cassandra.fullnameOverride }}

    kubernetes:
      useCustomConfig: false
      namespacePrefix: {{ .Values.infraMgr.kubernetes.namespacePrefix }}

      ingress: {{ .Values.infraMgr.kubernetes.ingress }}

      secretNames:
      {{- with .Values.infraMgr.kubernetes.secrets }}
        {{- toYaml . | nindent 6 }}
      {{- end }}

      configMaps:
      {{- with .Values.infraMgr.kubernetes.configMaps }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
