---
{{/*
Generating configMap for k8 with th2-infra info
*/}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: about
  labels:
    app: th2-info
data:
  about.yaml:
  {{- include "collect-info" . | trim | nindent 4 }}
