#FIXME: delete secrets once it will be deleted from operator resources https://github.com/th2-net/th2-infra-operator/tree/master/src/main/resources
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: git-chart-creds
  namespace: service
data:
  password: ""
  username: ""
