apiVersion: v1
data:
  log4j2.properties: |
    # Name of the configuration
    name=InfraLogger
    # Console appender configuration
    appender.console.type=Console
    appender.console.name=consoleLogger
    appender.console.layout.type=PatternLayout
    appender.console.layout.pattern=%d{dd MMM yyyy HH:mm:ss,SSS} %-6p [%-15t] %c - %m%n
    # Root logger level
    rootLogger.level=INFO
    # Root logger referring to console appender
    rootLogger.appenderRef.stdout.ref=consoleLogger
    logger.fabric8.name=io.fabric8.kubernetes.client.informers.cache
    logger.fabric8.level=WARN
kind: ConfigMap
metadata:
  name: logging-config
  annotations:
  {{- include "common-annotations" . | nindent 4  }}