apiVersion: v1
data:
  log4cxx.properties: |
    log4cxx::helpers::Properties properties;
    properties.setProperty(L"log4j.rootLogger",L"${LOGLEVEL_ROOT}");
    properties.setProperty(L"log4j.appender",L"ca");
    properties.setProperty(L"log4j.appender",L"fa");
  log4j.properties: |
    log4j.rootLogger=${LOGLEVEL_ROOT}, CON

    log4j.appender.CON=org.apache.log4j.ConsoleAppender
    log4j.appender.CON.layout=org.apache.log4j.PatternLayout
    log4j.appender.CON.layout.ConversionPattern=%d{dd MMM yyyy HH:mm:ss,SSS} %-6p [%-15t] %c - %m%n

    log4j.logger.com.exactpro.th2=${LOGLEVEL_JAVA}
    log4j.logger.com.exactpro.evolution=${LOGLEVEL_JAVA}
    log4j.logger.com.exactpro.cradle=${LOGLEVEL_JAVA}
<<<<<<< HEAD:th2-service/templates/configs/logging-configmap-template.yaml
    log4j.logger.com.exactpro.sf.services.http=${LOGLEVEL_JAVA}
=======
    log4j.logger.com.exactpro.sf=${LOGLEVEL_JAVA}
>>>>>>> origin/release-v1.8.0:chart/templates/configs/logging-configmap-template.yaml
  log4py.conf: |
    [loggers]
    keys=root,th2_common,pika
   
    [handlers]
    keys=consoleHandler
   
    [formatters]
    keys=formatter
   
    [logger_root]
    level=${LOGLEVEL_ROOT}
    handlers=consoleHandler
    propagate=0
   
    [logger_th2_common]
    level=${LOGLEVEL_PYTHON}
    qualname=th2_common
    handlers=consoleHandler
    propagate=0
   
    [logger_pika]
    level=${LOGLEVEL_PYTHON}
    qualname=pika
    handlers=consoleHandler
    propagate=0
   
    [handler_consoleHandler]
    class=StreamHandler
    formatter=formatter
    args=(sys.stdout,)
   
    [formatter_formatter]
    format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
  log4j2.properties: |
    name=Th2Logger
    # Console appender configuration
    appender.console.type=Console
    appender.console.name=consoleLogger
    appender.console.layout.type=PatternLayout
    appender.console.layout.pattern=%d{dd MMM yyyy HH:mm:ss,SSS} %-6p [%-15t] %c - %m%n
    # Root logger level
    rootLogger.level=${LOGLEVEL_ROOT}
    # Root logger referring to console appender
    rootLogger.appenderRef.stdout.ref=consoleLogger

    logger.th2.name=com.exactpro.th2
    logger.th2.level=${LOGLEVEL_JAVA}

    logger.evolution.name=com.exactpro.evolution
    logger.evolution.level=${LOGLEVEL_JAVA}

    logger.cradle.name=com.exactpro.cradle
    logger.cradle.level=${LOGLEVEL_JAVA}

<<<<<<< HEAD:th2-service/templates/configs/logging-configmap-template.yaml
    logger.sf.name=com.exactpro.sf.services.http
=======
    logger.sf.name=com.exactpro.sf
>>>>>>> origin/release-v1.8.0:chart/templates/configs/logging-configmap-template.yaml
    logger.sf.level=${LOGLEVEL_JAVA}
kind: ConfigMap
metadata:
  name: logging-config-template
  annotations:
  {{- include "common-annotations" . | nindent 4  }}
