{
 "title": "Infra Operator",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(th2_infra_operator_custom_resource_event_processing_time_count, exported_namespace)"
   },
   {
    "name": "kind",
    "query": "label_values(th2_infra_operator_custom_resource_event_processing_time_count{exported_namespace=\"$namespace\"}, kind)"
   },
   {
    "name": "resource",
    "query": "label_values(th2_infra_operator_custom_resource_event_processing_time_count{exported_namespace=\"$namespace\", kind=\"$kind\"}, resName)"
   },
   {
    "name": "configMap",
    "query": "label_values(th2_infra_operator_config_map_event_processing_time_count{exported_namespace=\"$namespace\"}, resName)"
   },
   {
    "name": "dictionary",
    "query": "label_values(th2_infra_operator_dictionary_event_processing_time_count{exported_namespace=\"$namespace\"}, resName)"
   },
   { "name": "search" }
  ]
 },
 "panels": [
  {
   "title": "logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log entries rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate({app=\"infra-operator\"} |~ \"(?i)$search\" [$__interval])"
      }
     ]
    },
    {
     "title": "logs",
     "type": "logs",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "{app=\"infra-operator\"} |~ \"(?i)$search\""
      }
     ]
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events to process",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "th2_infra_operator_event_queue{exported_namespace=\"${namespace}\"} "
      }
     ]
    },
    {
     "title": "Processing time (kind)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 18, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(th2_infra_operator_custom_resource_event_processing_time_bucket{le=\"5.0\", exported_namespace=\"${namespace}\",kind=\"${kind}\"}[1m])"
      }
     ]
    }
   ]
  },
  {
   "title": "Box event processing time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total processing time (specific resource)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(th2_infra_event_processing_total_time_bucket{le=\"50.0\", exported_namespace=\"${namespace}\",kind=\"${kind}\", resName=\"${resource}\"}[10m]))\n/\nsum(rate(th2_infra_event_processing_total_time_count{exported_namespace=\"${namespace}\",kind=\"${kind}\", resName=\"${resource}\"}[10m]))",
       "legendFormat": "less than equal to 50 seconds"
      }
     ]
    },
    {
     "title": "Operator event processing time (specific resource)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(th2_infra_operator_custom_resource_event_processing_time_bucket{le=\"5.0\", exported_namespace=\"${namespace}\",kind=\"${kind}\", resName=\"${resource}\"}[10m]))\n/\nsum(rate(th2_infra_operator_custom_resource_event_processing_time_count{exported_namespace=\"${namespace}\",kind=\"${kind}\", resName=\"${resource}\"}[10m]))",
       "legendFormat": "less than equal to 5 seconds"
      }
     ]
    }
   ]
  },
  {
   "title": "Dictionary and CM event processing time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Config map event processing time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(th2_infra_operator_config_map_event_processing_time_bucket{le=\"30.0\", exported_namespace=\"${namespace}\", resName=\"${configMap}\"}[10m]))\n/\nsum(rate(th2_infra_operator_config_map_event_processing_time_count{exported_namespace=\"${namespace}\", resName=\"${configMap}\"}[10m]))",
       "legendFormat": "less than equal to 30 seconds"
      }
     ]
    },
    {
     "title": "Dictionary event processing time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(th2_infra_operator_dictionary_event_processing_time_bucket{le=\"30.0\", exported_namespace=\"${namespace}\", resName=\"${dictionary}\"}[10m]))\n/\nsum(rate(th2_infra_operator_dictionary_event_processing_time_count{exported_namespace=\"${namespace}\", resName=\"${dictionary}\"}[10m]))",
       "legendFormat": "less than equal to 30 seconds"
      }
     ]
    }
   ]
  },
  {
   "title": "Event count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Event count (specific resource)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(th2_infra_operator_custom_resource_event_processing_time_count{exported_namespace=\"${namespace}\", kind=\"${kind}\", resName=\"${resource}\"}[10m])"
      }
     ]
    }
   ]
  }
 ]
}