{{- if not .Values.existingRegistrySecrets -}}
{{- range $registry, $values := .Values.registries }}
---
{{- $registry_name := $registry }}
{{- $secret_name := $registry | replace "." "-" | replace ":" "-" }}
apiVersion: v1
data:
  .dockerconfigjson: {{ printf `{"auths": {"%s": {"auth": "%s"}}}` $registry_name (printf "%s:%s" $values.username $values.password | b64enc) | b64enc }}
kind: Secret
metadata:
  name: {{ $secret_name }}
  {{- if $.Values.commonAnnotations }}
  annotations:
  {{- include "common-annotations" $ | nindent 4  }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
{{- end }}
