apiVersion: v1
data:
  token-v2: {{ .Values.arangodb.licenseKey | b64enc | quote }}
kind: Secret
metadata:
  name: arango-license-key
  namespace: {{ .Release.Namespace }}
  resourceVersion: "64655"
  selfLink: /api/v1/namespaces/default/secrets/arango-license-key
type: Opaque
