{{- if .Values.converter.git.repository }}
apiVersion: v1
kind: Secret
metadata:
  name: converter
  annotations:
  {{- include "common-annotations" . | nindent 4  }}
  labels:
    {{- include "th2-labels" . | nindent 4 }}
type: Opaque
data:
  {{- if hasPrefix "https" .Values.converter.git.repository}}
  httpAuthUsername: {{ .Values.converter.git.httpAuthUsername | b64enc | quote }}
  httpAuthPassword: {{ .Values.converter.git.httpAuthPassword | b64enc | quote }}
  {{- else }}
  id_ed25519: {{ required "Private key for converter is required. Please set converter.git.privateKey in base64" .Values.converter.git.privateKey }}
  {{- end }}
{{- end }}
