{{- if and (not .Values.cassandra.internal) (not .Values.cassandra.dbUser.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: cassandra
  annotations:
  {{- include "common-annotations" . | nindent 4  }}
  labels:
    {{- include "th2-labels" . | nindent 4 }}
type: Opaque
data:
  cassandra-password: {{ .Values.cassandra.dbUser.password | b64enc | quote }}
{{ end }}
