{{- if or (not .Values.rabbitmq.internal) (not .Values.rabbitmq.auth.existingPasswordSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  annotations:
  {{- include "common-annotations" . | nindent 4  }}
  labels:
    {{- include "th2-labels" . | nindent 4 }}
type: Opaque
data:
  rabbitmq-password: {{ .Values.rabbitmq.rabbitmqPassword | b64enc | quote }}
{{- end -}}
