{{- if not .Values.cassandra.internal -}}
apiVersion: v1
kind: Secret
metadata:
  name: cassandra
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "th2-labels" . | nindent 4 }}
type: Opaque
data:
  cassandra-password: {{ .Values.cassandra.dbUser.password | b64enc | quote }}
{{ end }}
