{{- if and (.Values.infraMgr.git.repository) (eq .Values.infraMgr.secretName "infra-mgr") }}
apiVersion: v1
kind: Secret
metadata:
  name: infra-mgr
  annotations:
  {{- include "common-annotations" . | nindent 4  }}
  labels:
    {{- include "th2-labels" . | nindent 4 }}
type: Opaque
data:
  {{- if hasPrefix "https" .Values.infraMgr.git.repository}}
  httpAuthUsername: {{ .Values.infraMgr.git.httpAuthUsername | b64enc | quote }}
  httpAuthPassword: {{ .Values.infraMgr.git.httpAuthPassword | b64enc | quote }}
  {{- else }}
  id_rsa: {{ required "Private key for infra-mgr is required. Please set infraMgr.git.privateKey in base64" .Values.infraMgr.git.privateKey }}
  {{- end }}
{{- end }}