apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.infraMgr.git.secretName }}
  annotations:
  {{- include "common-annotations" . | nindent 4  }}
  labels:
    {{- include "th2-labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not (hasPrefix "https" .Values.infraMgr.git.repository)}}
  {{- if .Values.infraMgr.git.privateKey }}
  id_rsa: {{ .Values.infraMgr.git.privateKey }}
  {{- end }}
  {{- else }}
  {{- if .Values.infraMgr.git.httpAuthUsername }}
  httpAuthUsername: {{ .Values.infraMgr.git.httpAuthUsername | b64enc | quote }}
  {{- end }}
  {{- if .Values.infraMgr.git.httpAuthPassword }}
  httpAuthPassword: {{ .Values.infraMgr.git.httpAuthPassword | b64enc | quote }}
  {{- end }}
  {{- end }}