{{- if or .Values.infraMgr.git.privateKey (and .Values.infraMgr.git.httpAuthUsername .Values.infraMgr.git.httpAuthPassword) }}
apiVersion: v1
kind: Secret
metadata:
  name: infra-mgr
  annotations:
  {{- include "common-annotations" . | nindent 4  }}
  labels:
    {{- include "th2-labels" . | nindent 4 }}
type: Opaque
data:
  {{- if hasPrefix "https" .Values.infraMgr.git.repository}}
  httpAuthUsername: {{ .Values.infraMgr.git.httpAuthUsername | b64enc | quote }}
  httpAuthPassword: {{ .Values.infraMgr.git.httpAuthPassword | b64enc | quote }}
  {{- else }}
  id_rsa: {{ .Values.infraMgr.git.privateKey }}
  {{- end }}
{{- end }}