---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
    name: arangodeployments.database.arangodb.com
    labels:
        app.kubernetes.io/name: kube-arangodb-crd
        helm.sh/chart: kube-arangodb-crd-1.2.20
        app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/instance: crd
        release: crd
spec:
  group: database.arangodb.com
  names:
    kind: ArangoDeployment
    listKind: ArangoDeploymentList
    plural: arangodeployments
    shortNames:
      - arangodb
      - arango
    singular: arangodeployment
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
    - name: v1alpha
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: false
    - name: v2alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: false
      subresources:
        status: {}