---
apiVersion: v1
kind: ConfigMap
metadata:
  {{- if .Values.annotations }}
  annotations:
    th2.exactpro.com/antecedent: {{ .Values.annotations }}
  {{- end }}
  name: {{ .Values.component.name }}-app-config
  labels:
    app: {{ .Values.component.name }}
data: 
  custom.json: |
    {{ .Values.component.custom | toJson }}
  grpc.json: |
    {{ .Values.component.grpcRouter | toJson }}
  mq.json: |
    {{ .Values.component.routerMq | toJson }}
  {{- if .Values.component.prometheus }}
  prometheus.json: |
    {{ .Values.component.prometheus | toJson }}
  {{- end }}
