{{- if not .Values.component.prometheus }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component.name }}-monitor
  {{- if .Values.annotations }}
  annotations:
    th2.exactpro.com/antecedent: {{ .Values.annotations }}
  {{- end }}
spec:
  selector:
    monitoring-pod: "true"
  ports:
    - name: metrics
      protocol: TCP
      port: 9752
      targetPort: metrics
{{- else }}
{{- if .Values.component.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component.name }}-monitor
  {{- if .Values.annotations }}
  annotations:
    th2.exactpro.com/antecedent : {{ .Values.annotations }}
  {{- end }}
spec:
  selector:
    monitoring-pod: "true"
  ports:
    - name: metrics
      protocol: TCP
      {{- if .Values.component.prometheus.port }}
      port: {{ .Values.component.prometheus.port }}
      {{- else }}
      port: 9752
      {{- end }}
      targetPort: metrics
{{- end }}
{{- end }}
