---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: ingress-rules
spec:
  rules:
  {{- if .Values.ingress.host }}
  - host: "{{ .Values.ingress.host -}}"
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
      - path: /{{ .Release.Namespace }}/backend/(rootEvents$|messageStreams$|((search|message|event)/.*))
        backend:
          serviceName: rpt-data-provider
          servicePort: 8080
      - path: /{{ .Release.Namespace }}/(.*)
        backend:
          serviceName: rpt-data-viewer
          servicePort: 8080
