{{- if not .Values.cassandra.internal -}}
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  annotations:
  {{- include "common-annotaitions" . | nindent 4  }}
spec:
  type: ExternalName
  externalName: {{ .Values.cassandra.host }}
{{ end }}
