{{- if not .Values.rabbitmq.internal -}}
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  annotations:
  {{- include "common-annotaitions" . | nindent 4  }}
spec:
  type: ExternalName
  externalName: {{ .Values.rabbitmq.host }}
{{ end }}
