name: e2e test Kubernetes 1.23

on:
  pull_request:
    paths:
      - "ci/**"
      - "example-values/**"
      - "chart/**"
      - "box-chart/**"
      - ".github/workflows/e2e-test.yml"
  workflow_dispatch:
    inputs:
      infraNamespace:
        description: "Infra namespace"
        default: "service"
        type: string
      schemaNamespace:
        description: "Schema namespace"
        default: "th2-schema"
        type: string

env:
  INFRA_NAMESPACE: "${{ github.event.inputs.infraNamespace || 'service' }}"
  MONITORING_NAMESPACE: monitoring
  SCHEMA_NAMESPACE: "${{ github.event.inputs.schemaNamespace || 'th2-schema' }}"
  REPOSITORY_URL: "${{ github.event.pull_request.base.repo.clone_url }}"
  REPOSITORY_REF_NAME: "${{ github.event.pull_request.head.ref }}"

jobs:
  deploy-and-test:
    if: |
      !contains(github.event.pull_request.labels, 'automated')
    runs-on: ubuntu-latest
    steps:
      - name: Go cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: actions/checkout@v2

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        with:
          config: ./ci/kind-cluster.yaml
          version: v0.11.1
          node_image: kindest/node:v1.23.6@sha256:1af0f1bee4c3c0fe9b07de5e5d3fafeb2eec7b4e1b268ae89fcab96ec67e8355

      - name: Init test schema
        run: |
          mkdir ./e2e-test-schema.git/
          git config --global user.email "ci@actions"
          git config --global user.name "CI"
          git --git-dir=./e2e-test-schema.git/ --bare init
          git --git-dir=./e2e-test-schema.git/ --work-tree=./ci/e2e-test-schema/ add .
          git --git-dir=./e2e-test-schema.git/ --work-tree=./ci/e2e-test-schema/ commit -m "Init repo"
          git --git-dir=./e2e-test-schema.git/ --work-tree=./ci/e2e-test-schema/ branch schema
          docker exec chart-testing-control-plane mkdir -p /opt/git/
          docker cp ./e2e-test-schema.git/ chart-testing-control-plane:/opt/git/

      - name: Install python and ansible dependencies
        run: |
          ansible-galaxy collection install community.crypto:==1.3.0 community.kubernetes:==1.1.1
          pip install kubernetes==12.0.0

      - name: Run th2-infra deployment via Ansible
        run: |
          ANSIBLE_STDOUT_CALLBACK=yaml ansible-playbook ./ci/e2e-via-ssh-deployment-playbook.yaml -e 'ansible_python_interpreter=/usr/bin/python3'
          kubectl -n $INFRA_NAMESPACE patch deployments.apps infra-mgr -p '{"spec":{"template":{"spec":{"initContainers":[{"name":"init-myservice","image":"busybox:1.30.1","command":["sh","-c","until nc -vz infra-git 22; do echo \"Waiting for infra-git service\"; sleep 2; done;"]}]}}}}'
          kubectl -n $INFRA_NAMESPACE patch deployments.apps infra-operator -p '{"spec":{"template":{"spec":{"initContainers":[{"name":"init-myservice","image":"busybox:1.30.1","command":["sh","-c","until nc -vz rabbitmq 5672; do echo \"Waiting for rabbitmq service\"; sleep 2; done;"]}]}}}}'
          kubectl get pods --all-namespaces

      - name: Testing
        run: |
          cd ./ci
          go test -failfast th2_infra_test.go

      - name: Getting logs
        if: always()
        run: |
          echo -e "\n[Pods]" && kubectl get pods -o wide --all-namespaces || true
          echo -e "\n[Services]" && kubectl get svc --all-namespaces || true
          echo -e "\n[Ingresses]" && kubectl describe ingress --all-namespaces || true
          echo -e "\n[HelmReleases]" && kubectl get hr --all-namespaces || true
          echo -e "\n[Nodes]" && kubectl describe nodes || true
          echo -e "\n[Configmaps]" && kubectl get configmaps --all-namespaces || true
          echo -e "\n[Secrets]" && kubectl get secrets --all-namespaces || true
          echo -e "\n[Events]" && kubectl get events --all-namespaces --sort-by='.metadata.creationTimestamp' || true
          echo -e "\n[PV]" && kubectl get pv || true

          for D in $(kubectl -n $INFRA_NAMESPACE get deployments --no-headers -o custom-columns=":metadata.name")
          do
            kubectl -n $INFRA_NAMESPACE logs deployment/$D --all-containers --timestamps > $D.log || true
          done
          kubectl -n $INFRA_NAMESPACE logs cassandra-0 > cassandra.log || true
          kubectl -n $INFRA_NAMESPACE exec cassandra-0 -- cat /opt/bitnami/cassandra/logs/cassandra.log > cassandra-container.log || true

          for D in $(kubectl -n $SCHEMA_NAMESPACE get deployments --no-headers -o custom-columns=":metadata.name")
          do
            kubectl -n $SCHEMA_NAMESPACE logs deployment/$D --timestamps > $D.log || true
          done

      - name: Uploading logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: infra-logs
          path: "*.log"
