name: e2e test with kind

on: push

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0
        with:
                config: ./.github/workflows/cluster.yaml
      - name: Run Ansible Playbook
        run: ansible-playbook -v ./.github/workflows/e2e-deploy-playbook.yaml
