name: Auto generate helm-docs

on:
  pull_request:
    paths:
      - "th2-service/**"
      - ".github/workflows/helm-docs.yaml"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate helm docs
        run: make docs
