name: Auto generate helm-docs

on:
  pull_request:
    paths:
      - "th2-service/**"
      - ".github/workflows/helm-docs.yaml"
  workflow_dispatch:

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate helm docs
        run: make docs

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update helm docs
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          base: ${{ github.event.pull_request.base.ref }}
          branch: example-patches
          delete-branch: true
          title: 'Auto-update helm docs'
          labels: |
            automated
