name: Lint and unit test infra chart
on:
  pull_request:
    paths:
      - "ci/**"
      - "example-values/**"
      - "chart/**"
      - ".github/workflows/lint-unit-test-chart.yaml"
  workflow_dispatch:

jobs:
  lint-test:
    if: |
      !contains(github.event.pull_request.labels, 'automated')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.1

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1
      
      - name: run unit test
        run: |
          helm plugin install https://github.com/quintush/helm-unittest
          helm unittest -3 chart --color -o ./test-results/chart-test-results.xml -t JUnit
      
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "./test-results/*.xml"

      - name: Run infra chart linting
        run: |
          ct lint \
            --chart-repos rabbitmq=https://charts.bitnami.com/bitnami,helm-operator=https://charts.fluxcd.io,kubernetes-dashboard=https://kubernetes.github.io/dashboard \
            --lint-conf=./ci/cfg/lint-cfg.yml \
            --check-version-increment \
            --validate-maintainers=false --debug --charts ./chart
