name: Lint and unit test box chart
permissions:
  checks: write
  pull-requests: write
on:
  pull_request:
    paths:
      - "box-chart/**"
      - ".github/workflows/lint-unit-test-box-chart.yaml"
  workflow_dispatch:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.1

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1
      
      - name: run unit test
        run: |
          helm plugin install https://github.com/quintush/helm-unittest
          helm unittest -3 box-chart --color -o ./tests/box-chart-test-results/hostAliases-test-results.xml -t JUnit
      
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "./tests/**/*.xml"

      - name: Run box chart linting
        run: |
          ct lint \
            --lint-conf=ci/cfg/lint-cfg.yml \
            --check-version-increment \
            --validate-maintainers=false --debug --charts ./box-chart
